### ISSUE TITLE
Cannot load DiT object detection weights

### ISSUE THREAD

**Issue by SAOHPRWHG** [microsoft/unilm#1246]
I try to do some inference on DiT-object detection Mask-RCNN-base model.
When I use this new weights in https://github.com/microsoft/unilm/commit/5255d52de86dad642810f5849dd357769346c1d7, I meet a new bug:
......
--opts MODEL.WEIGHTS ./archive/data.pkl
Traceback (most recent call last):
File "/mnt/backup2/home/szyu22/dit/object_detection/pdf2txt_dit.py", line 104, in
process_pdf(args.pdf_dir, args.save_images, args.outputs_dir, args.config_file, args.opts)
File "/mnt/backup2/home/szyu22/dit/object_detection/pdf2txt_dit.py", line 62, in process_pdf
detections = detect_objects(image_path, config_file, opts)
File "/mnt/backup2/home/szyu22/dit/object_detection/pdf2txt_dit.py", line 29, in detect_objects
weights = torch.load(weights_path)
File "/mnt/home/szyu22/anaconda3/envs/dit/lib/python3.10/site-packages/torch/serialization.py", line 713, in load
return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
File "/mnt/home/szyu22/anaconda3/envs/dit/lib/python3.10/site-packages/torch/serialization.py", line 920, in _legacy_load
magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: A load persistent id instruction was encountered,
but no persistent_load function was specified.

Could you please tell me how to fix this bug? Thanks for your support!

**Comment by bit-scientist** [comment]
Same is happening to me as described here #1248. Could you share the running command or file that is causing this?

**Comment by Qucy** [comment]
You can download zip weights file and change the MODEL WEIGHTS point to zip file, I can get the output image by using below command, hope this can help you.

python ./dit/object_detection/inference.py \
--image_path ./dit/object_detection/publaynet_example.jpeg \
--output_file_name output.jpg \
--config ./dit/object_detection/publaynet_configs/maskrcnn/maskrcnn_dit_base.yaml \
--opts MODEL.WEIGHTS publaynet_dit-b_mrcnn.zip

**Comment by hassanhajj910** [comment]
> You can download zip weights file and change the MODEL WEIGHTS point to zip file, I can get the output image by using below command, hope this can help you.
> 
> python ./dit/object_detection/inference.py --image_path ./dit/object_detection/publaynet_example.jpeg --output_file_name output.jpg --config ./dit/object_detection/publaynet_configs/maskrcnn/maskrcnn_dit_base.yaml --opts MODEL.WEIGHTS publaynet_dit-b_mrcnn.zip

This worked for me, thanks!
