### ISSUE TITLE
[Vlmo]  error with Step 3: Vision-Language Pre-Training (VLMo-Base)

### ISSUE THREAD

**Issue by CHB-learner** [microsoft/unilm#1254]
my  command:

python run.py with data_root=./data_model_pth/data_arrows_root/ num_gpus=1 num_nodes=1 task_mlm_itm_itc_base whole_word_masking=True step200k per_gpu_batchsize=8 load_path=$INIT_CKPT log_dir=./data_model_pth/Output/
WARNING - VLMo - No observers have been added to this run
INFO - VLMo - Running command 'main'
INFO - VLMo - Started
Global seed set to 1
ERROR - VLMo - Failed after 0:01:20!
Traceback (most recent call last):
  File "/home/**********/anaconda3/envs/**********/lib/python3.8/site-packages/sacred/experiment.py", line 312, in run_commandline
    return self.run(
  File "/home/**********/anaconda3/envs/**********/lib/python3.8/site-packages/sacred/experiment.py", line 276, in run
    run()
  File "/home/**********/anaconda3/envs/**********/lib/python3.8/site-packages/sacred/run.py", line 238, in __call__
    self.result = self.main_function(*args)
  File "/home/**********/anaconda3/envs/**********/lib/python3.8/site-packages/sacred/config/captured_function.py", line 42, in captured_function
    result = wrapped(*args, **kwargs)
  File "run.py", line 73, in main
    dm = MTDataModule(_config, dist=True)
  File "/home/**********/Share_data/**********/unilm/vlmo/vlmo/datamodules/multitask_datamodule.py", line 19, in __init__
    self.dm_dicts = {key: _datamodules[key](_config) for key in datamodule_keys}
  File "/home/**********/Share_data/**********/unilm/vlmo/vlmo/datamodules/multitask_datamodule.py", line 19, in <dictcomp>
    self.dm_dicts = {key: _datamodules[key](_config) for key in datamodule_keys}
  File "/home/**********/Share_data/**********/unilm/vlmo/vlmo/datamodules/coco_caption_karpathy_datamodule.py", line 7, in __init__
    super().__init__(*args, **kwargs)
  File "/home/**********/Share_data/**********/unilm/vlmo/vlmo/datamodules/datamodule_base.py", line 54, in __init__
    self.tokenizer = get_pretrained_tokenizer(tokenizer)
  File "/home/**********/Share_data/**********/unilm/vlmo/vlmo/datamodules/datamodule_base.py", line 19, in get_pretrained_tokenizer
    return BertTokenizer.from_pretrained(
  File "/home/**********/anaconda3/envs/**********/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 1672, in from_pretrained
    resolved_vocab_files[file_id] = cached_path(
  File "/home/**********/anaconda3/envs/**********/lib/python3.8/site-packages/transformers/file_utils.py", line 1329, in cached_path
    output_path = get_from_cache(
  File "/home/**********/anaconda3/envs/**********/lib/python3.8/site-packages/transformers/file_utils.py", line 1552, in get_from_cache
    raise ValueError(
ValueError: Connection error, and we cannot find the requested files in the cached path. Please try again or make sure your Internet connection is on.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 69, in <module>
    def main(_config):
  File "/home/**********/anaconda3/envs/**********/lib/python3.8/site-packages/sacred/experiment.py", line 190, in automain
    self.run_commandline()
  File "/home/**********/anaconda3/envs/**********/lib/python3.8/site-packages/sacred/experiment.py", line 347, in run_commandline
    print_filtered_stacktrace()
  File "/home/**********/anaconda3/envs/**********/lib/python3.8/site-packages/sacred/utils.py", line 493, in print_filtered_stacktrace
    print(format_filtered_stacktrace(filter_traceback), file=sys.stderr)
  File "/home/**********/anaconda3/envs/**********/lib/python3.8/site-packages/sacred/utils.py", line 528, in format_filtered_stacktrace
    return "".join(filtered_traceback_format(tb_exception))
  File "/home/**********/anaconda3/envs/**********/lib/python3.8/site-packages/sacred/utils.py", line 568, in filtered_traceback_format
    current_tb = tb_exception.exc_traceback
AttributeError: 'TracebackException' object has no attribute 'exc_traceback'

**Comment by wenhui0924** [comment]
Hi @CHB-learner, the error may be because of the download failure of the tokenizer file ("ValueError: Connection error, and we cannot find the requested files in the cached path. Please try again or make sure your Internet connection is on.").

**Comment by CHB-learner** [comment]
> Hi @CHB-learner, the error may be because of the download failure of the tokenizer file ("ValueError: Connection error, and we cannot find the requested files in the cached path. Please try again or make sure your Internet connection is on.").

Is it my Internet problem? If so, can I download it manually? Because my remote server may not be able to access the Internet.

**Comment by CHB-learner** [comment]
Do you have any suggestions regarding this issue?

**Comment by wenhui0924** [comment]
You can refer to the transformers library, the tokenizer file is downloaded from the internet via transformers repo.

**Comment by CHB-learner** [comment]
Thanks~!!
solved command

TRANSFORMERS_OFFLINE=1  python run.py ..............................
