### ISSUE TITLE
[BEIT3] How to apply GradCam on the beit3 models?

### ISSUE THREAD

**Issue by TheNha** [microsoft/unilm#1275]
Hi. I want to see the gradcam image of the beit3 model. I used the grad-cam library [https://github.com/jacobgil/pytorch-grad-cam], but I got this error. 'RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn'.
Please help..
Thank you!

**Comment by wenhui0924** [comment]
Could you provide more information about how you see the gradcam image of the beit3 model?

**Comment by TheNha** [comment]
I can't export the gradcam image of the beit3 model. I'm using the grad-cam library to export. But it got the error as above.

**Comment by wenhui0924** [comment]
Sorry, I do not know why. But could you print the name of the param where the error occurs?

**Comment by TheNha** [comment]
Thank you. 
This is error log.
Traceback (most recent call last):
  File "show_gradcam_beit3.py", line 108, in <module>
    grayscale_cam = cam(input_tensor=input_tensor,
  File "/home/coreai/anaconda3/envs/fake-image-detection/lib/python3.8/site-packages/pytorch_grad_cam/base_cam.py", line 188, in __call__
    return self.forward(input_tensor,
  File "/home/coreai/anaconda3/envs/fake-image-detection/lib/python3.8/site-packages/pytorch_grad_cam/base_cam.py", line 84, in forward
    loss.backward(retain_graph=True)
  File "/home/coreai/anaconda3/envs/fake-image-detection/lib/python3.8/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/home/coreai/anaconda3/envs/fake-image-detection/lib/python3.8/site-packages/torch/autograd/__init__.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

**Comment by donglixp** [comment]
It seems that the issue was caused by the pytorch-grad-cam package.

**Comment by TheNha** [comment]
Hi @donglixp, 
Is there any way to export the gradcam image of beit3 model?
