### ISSUE TITLE
[VLMO] Step 3: Vision-Language Pre-Training (VLMo-Base) Error

### ISSUE THREAD

**Issue by CHB-learner** [microsoft/unilm#1281]
vlmo/datasets/base_dataset.py : (for debug)
......
        if len(names) != 0:
            tables = [
                pa.ipc.RecordBatchFileReader(
                    pa.memory_map(f"{data_dir}/{name}.arrow", "r")
                ).read_all()
                for name in names
                if os.path.isfile(f"{data_dir}/{name}.arrow")
            ]
            print('- - - - - - - - - - - - - - - - - - - - - - - - ')
            print('tables: \n',tables,'\n')
            print('names: \n',names,'\n')
            self.table_names = list()
            for i, name in enumerate(names):
                self.table_names += [name] * len(tables[i])
                print('i: \n',i)
                print('name:',name,'\n')

            self.table = pa.concat_tables(tables, promote=True)
......

-----------------------------------
my data:
data_arrows_root
├── coco_caption_karpathy_restval.arrow
├── coco_caption_karpathy_test.arrow
├── coco_caption_karpathy_train.arrow
└── coco_caption_karpathy_val.arrow

run as:

export INIT_CKPT=/home/ubuntu/XXX/unilm/vlmo/1_My_Vlmo/pth/vlmo_base_patch16_224_stage2.pt

TRANSFORMERS_OFFLINE=1 python run.py with data_root=/home/ubuntu/XXX/unilm/vlmo/data/data_arrows_root/ num_gpus=1 num_nodes=1 task_mlm_itm_itc_base whole_word_masking=True step200k per_gpu_batchsize=8 load_path=$INIT_CKPT log_dir=./out/

-----------------------------------
# result
/home/ubuntu/miniconda3/envs/vlmo/lib/python3.8/site-packages/torchvision/transforms/transforms.py:803: UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.
  warnings.warn(
- - - - - - - - - - - - - - - - - - - - - - - - 
tables: 
 [pyarrow.Table
image: binary
caption: list<item: string>
  child 0, item: string
image_id: string
split: string, pyarrow.Table
image: binary
caption: list<item: string>
  child 0, item: string
image_id: string
split: string] 

names: 
 ['coco_caption_karpathy_train', 'coco_caption_karpathy_restval'] 

i: 
 0
name: coco_caption_karpathy_train 

i: 
 1
name: coco_caption_karpathy_restval 

- - - - - - - - - - - - - - - - - - - - - - - - 
tables: 
 [pyarrow.Table
image: binary
caption: list<item: string>
  child 0, item: string
image_id: string
split: string] 

names: 
 ['coco_caption_karpathy_val'] 

i: 
 0
name: coco_caption_karpathy_val 

- - - - - - - - - - - - - - - - - - - - - - - - 
tables: 
 [pyarrow.Table
image: binary
caption: list<item: string>
  child 0, item: string
image_id: string
split: string] 

names: 
 ['coco_caption_karpathy_val'] 

i: 
 0
name: coco_caption_karpathy_val 

- - - - - - - - - - - - - - - - - - - - - - - - 
tables: 
 [pyarrow.Table
image: binary
caption: list<item: string>
  child 0, item: string
image_id: string
split: string] 

names: 
 ['coco_caption_karpathy_test'] 

i: 
 0
name: coco_caption_karpathy_test 

- - - - - - - - - - - - - - - - - - - - - - - - 
tables: 
 [] 

names: 
 ['vg'] 

ERROR - VLMo - Failed after 0:00:05!
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/vlmo/lib/python3.8/site-packages/sacred/experiment.py", line 312, in run_commandline
    return self.run(
  File "/home/ubuntu/miniconda3/envs/vlmo/lib/python3.8/site-packages/sacred/experiment.py", line 276, in run
    run()
  File "/home/ubuntu/miniconda3/envs/vlmo/lib/python3.8/site-packages/sacred/run.py", line 238, in __call__
    self.result = self.main_function(*args)
  File "/home/ubuntu/miniconda3/envs/vlmo/lib/python3.8/site-packages/sacred/config/captured_function.py", line 42, in captured_function
    result = wrapped(*args, **kwargs)
  File "run.py", line 166, in main
    trainer.fit(model, datamodule=dm)
  File "/home/ubuntu/miniconda3/envs/vlmo/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 737, in fit
    self._call_and_handle_interrupt(
  File "/home/ubuntu/miniconda3/envs/vlmo/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 682, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/vlmo/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 772, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/ubuntu/miniconda3/envs/vlmo/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1134, in _run
    self._call_setup_hook()  # allow user to setup lightning_module in accelerator environment
  File "/home/ubuntu/miniconda3/envs/vlmo/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1434, in _call_setup_hook
    self.datamodule.setup(stage=fn)
  File "/home/ubuntu/miniconda3/envs/vlmo/lib/python3.8/site-packages/pytorch_lightning/core/datamodule.py", line 474, in wrapped_fn
    fn(*args, **kwargs)
  File "/home/ubuntu/Zuolab/unilm/vlmo/vlmo/datamodules/multitask_datamodule.py", line 34, in setup
    dm.setup(stage)
  File "/home/ubuntu/miniconda3/envs/vlmo/lib/python3.8/site-packages/pytorch_lightning/core/datamodule.py", line 474, in wrapped_fn
    fn(*args, **kwargs)
  File "/home/ubuntu/Zuolab/unilm/vlmo/vlmo/datamodules/datamodule_base.py", line 150, in setup
    self.set_train_dataset()
  File "/home/ubuntu/Zuolab/unilm/vlmo/vlmo/datamodules/datamodule_base.py", line 77, in set_train_dataset
    self.train_dataset = self.dataset_cls(
  File "/home/ubuntu/Zuolab/unilm/vlmo/vlmo/datasets/vg_caption_dataset.py", line 15, in __init__
    super().__init__(*args, **kwargs, names=names, text_column_name="caption")
  File "/home/ubuntu/Zuolab/unilm/vlmo/vlmo/datasets/base_dataset.py", line 55, in __init__
    self.table_names += [name] * len(tables[i])
IndexError: list index out of range

**Comment by CHB-learner** [comment]
why return 

tables: 
 [] 

names: 
 ['vg']

**Comment by wenhui0924** [comment]
It seems that you only use COCO data for training/debug. Do you modify datasets = ["coco", "vg", "sbu", "GCC"] to ["coco"]?

**Comment by CHB-learner** [comment]
Thank you! My code is running. 
Is it feasible to train step1-3 using only the coco dataset? 

If I want to train on my own data set, do I need to organize it into coco format?

**Comment by CHB-learner** [comment]
> It seems that you only use COCO data for training/debug. Do you modify datasets = ["coco", "vg", "sbu", "GCC"] to ["coco"]?

Thank you! My code is running.
Is it feasible to train step1-3 using only the coco dataset?

If I want to train on my own data set, do I need to organize it into coco format?

**Comment by wenhui0924** [comment]
Yes, you can train the model only on COCO data, but the performance might be lower and you need to try different hyperparameters. You can also train the model on your own dataset if you use the data class of COCO.
