### ISSUE TITLE
Issue with lxml during document classification training

### ISSUE THREAD

**Issue by andrewcby** [microsoft/unilm#130]
I set up the model for training for document classification task. Followed the instructions on README page. However, usually a minute or so into training, I would get an error as below:
我按照README把数据和模型都准备好，用来做文档分类的工作。但运行training的代码，大约30秒到1分钟左右，出现下列错误，跟lxml有关：
```
Traceback (most recent call last):
  File "run_classification.py", line 858, in <module>
    main()
  File "run_classification.py", line 790, in main
    args, args.task_name, tokenizer, evaluate=False
  File "run_classification.py", line 418, in load_and_cache_examples
    else processor.get_train_examples(args.data_dir)
  File "/databricks/driver/unilm/layoutlm/utils_classification.py", line 104, in get_train_examples
    text, bbox = self.read_hocr_file(data_dir, file)
  File "/databricks/driver/unilm/layoutlm/utils_classification.py", line 125, in read_hocr_file
    for page in doc.xpath("//*[@class='ocr_page']"):
  File "src/lxml/etree.pyx", line 2292, in lxml.etree._ElementTree.xpath
  File "src/lxml/etree.pyx", line 1870, in lxml.etree._ElementTree._assertHasRoot
AssertionError: ElementTree not initialized, missing root
```
I tried installing the latest version of lxml (4.5), with my original version being 4.3, and it did not resolve the issue. Any pointers on how I might be able to resolve this issue? Thanks!
我尝试把lxml从原来的4.3版本更新的4.5，但还是有相同的问题。不知道这个该怎么解决，谢谢！

**Comment by ranpox** [comment]
Hi @andrewcby ,
It seems that there are some empty files or their formats are unacceptable. I have added [exception handling](https://github.com/microsoft/unilm/blob/63ed32b9fb7c33df3e9beea427b54c0bfb196556/layoutlm/utils_classification.py#L124) for lxml parsing. Please pull the latest code and check the warning data files.
Thanks.
