### ISSUE TITLE
About textdiffuser evaluation code

### ISSUE THREAD

**Issue by samsara-ku** [microsoft/unilm#1302]
I have a problem with testing ControlNet generation result.

I want to launch the code with respect to the dataset `TMDBEval500`, but `fid_score.py` doesn't work at all with below error:

```
Traceback (most recent call last):
  File "~/evaluation_score.py", line 142, in <module>
    MARIOEval_evaluate_results(
  File "~/evaluation_score.py", line 66, in MARIOEval_evaluate_results
    fids.append(calculate_fid_given_paths(paths=[gt_path, gen_path]))
  File "~fidscore.py", line 240, in calculate_fid_given_paths
    fid_value = calculate_frechet_distance(m1, s1, m2, s2)
  File "~fidscore.py", line 167, in calculate_frechet_distance
    raise ValueError('Imaginary component {}'.format(m))
ValueError: Imaginary component 4.4366181668338115e+90
```

How can I solve this problem?

**Comment by samsara-ku** [comment]
I figure out the what is [wrong](https://github.com/mseitzer/pytorch-fid/issues/29), so close this now.
