### ISSUE TITLE
index out of range - LayoutLM sequence labelling

### ISSUE THREAD

**Issue by sukumar-varma** [microsoft/unilm#131]
I've been trying to run the sequence labelling fine-tuning task on a custom dataset of 150 samples but it keeps running into index out of range error. The following is the traceback:
```2020-05-12 04:42:21.741984: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2020-05-12 04:42:21.749427: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2199995000 Hz
2020-05-12 04:42:21.749844: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55ae2f2747d0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-05-12 04:42:21.749881: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-05-12 04:42:21.750570: I tensorflow/core/common_runtime/process_util.cc:147] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
Epoch:   0%|                                                                                                          | 0/100 [00:00<?, ?it/sTraceback (most recent call last):                                                                                       | 0/4 [00:00<?, ?it/s]
  File "run_seq_labeling.py", line 857, in <module>
    main()
  File "run_seq_labeling.py", line 752, in main
    args, train_dataset, model, tokenizer, labels, pad_token_label_id
  File "run_seq_labeling.py", line 215, in train
    outputs = model(**inputs)
  File "/root/anaconda3/envs/layoutlm/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/sukumar/layoutlm/modeling_layoutlm.py", line 253, in forward
    head_mask=head_mask,
  File "/root/anaconda3/envs/layoutlm/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/sukumar/layoutlm/modeling_layoutlm.py", line 190, in forward
    input_ids, bbox, position_ids=position_ids, token_type_ids=token_type_ids,
  File "/root/anaconda3/envs/layoutlm/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/sukumar/layoutlm/modeling_layoutlm.py", line 59, in forward
    left_position_embeddings = self.x_position_embeddings(bbox[:, :, 0])
  File "/root/anaconda3/envs/layoutlm/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/envs/layoutlm/lib/python3.6/site-packages/torch/nn/modules/sparse.py", line 114, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "/root/anaconda3/envs/layoutlm/lib/python3.6/site-packages/torch/nn/functional.py", line 1484, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: index out of range: Tried to access index 1115 out of table with 1023 rows. at /opt/conda/conda-bld/pytorch_1573049304260/work/aten/src/TH/generic/THTensorEvenMoreMath.cpp:418
Epoch:   0%|                                                                                                          | 0/100 [00:00<?, ?it/s]
Iteration:   0%|                                                                                                        | 0/4 [00:00<?, ?it/s]
```
I've tried changing the vocab size in the model config but that again throws a size mismatch error. Is there any other way I can pass in custom vocab sizes?

**Comment by ranpox** [comment]
Hi @sukumar-varma ,
Thanks for your feedback.
Please make sure that you have normalized the bounding box like [this](https://github.com/microsoft/unilm/blob/master/layoutlm/scripts/funsd_preprocess.py#L8) before passing your custom dataset into LayoutLM.

For vocab size, you can use [`resize_token_embeddings`](https://github.com/huggingface/transformers/blob/30e343862f0f78512faae0374fc39898bd00ce95/src/transformers/modeling_utils.py#L324) to resize the vocab.

**Comment by sukumar-varma** [comment]
Thanks, that did the trick.

**Comment by hasansalimkanmaz** [comment]
@ranpox  could you elaborate on how to `resize_token_embeddings`?
