### ISSUE TITLE
[Beit3] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 65181 closing signal SIGTERM.

### ISSUE THREAD

**Issue by jinqin-99** [microsoft/unilm#1351]
I want to finetune Beit3 on COCO Caption
When  computing Bleu score , the error emerge

The code is
`python -m torch.distributed.launch --nproc_per_node=4 run_beit3_finetuning.py \
        --model beit3_base_patch16_480 \
        --input_size 480 \
        --task coco_captioning \
        --batch_size 32 \
        --layer_decay 1.0 \
        --lr 4e-5 \
        --randaug \
        --epochs 10 \
        --warmup_epochs 1 \
        --drop_path 0.1 \
        --sentencepiece_model ./beit3.spm \
        --finetune ./checkpoint/beit3_base_patch16_224.pth \
        --data_path ./dataset \
        --output_dir ./save \
        --log_dir ./save/log \
        --weight_decay 0.05 \
        --seed 42 \
        --save_ckpt_freq 5 \
        --num_max_bpe_tokens 32 \
        --captioning_mask_prob 0.7 \
        --drop_worst_after 12000 \
        --dist_eval \
        --checkpoint_activations \
        --enable_deepspeed`

The environment is
python 3.9
troch 2.1.0

The partial of log is

Test: Total time:0:01:24 (2.1691 s / it)
Infer 4992 examples into ./save/submit_coco_captioning_val_e0.json
Using downloaded and verified file: ./save/coco_karpathy_val_gt.json
loading annotations into memory...
Done (t=0.04s)
creating index...
index created!
Loading and preparing results...
DONE (t=0.01s)
creating index...
index created!
tokenization...
PTBTokenizer tokenized 307821 tokens at 1151316.74 tokens per second.
PTBTokenizer tokenized 60431 tokens at 410147.53 tokens per second.
setting up scorers...
computing Bleu score...
Traceback (most recent call last):
  File "/home/y/python/projects/beit3/run_beit3_finetuning.py", line 451, in <module>
    main(opts, ds_init)
  File "/home/y/python/projects/beit3/run_beit3_finetuning.py", line 408, in main
    test_stats = utils.coco_caption_eval(args.output_dir, prediction_file, "{}_val".format(args.task))
  File "/home/y/python/projects/beit3/utils.py", line 907, in coco_caption_eval
    coco_eval.evaluate()
  File "/home/y/miniconda3/envs/Beit3/lib/python3.9/site-packages/pycocoevalcap/eval.py", line 53, in evaluate
    score, scores = scorer.compute_score(gts, res)
  File "/home/y/miniconda3/envs/Beit3/lib/python3.9/site-packages/pycocoevalcap/bleu/bleu.py", line 23, in compute_score
    assert(gts.keys() == res.keys())
AssertionError
[2023-11-03 14:50:46,818] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 65181 closing signal SIGTERM
[2023-11-03 14:50:46,819] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 65182 closing signal SIGTERM
[2023-11-03 14:50:46,820] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 65183 closing signal SIGTERM
[2023-11-03 14:50:48,701] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 65180) of binary: /home/y/miniconda3/envs/Beit3/bin/python
Traceback (most recent call last):
  File "/home/y/miniconda3/envs/Beit3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/y/miniconda3/envs/Beit3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/y/miniconda3/envs/Beit3/lib/python3.9/site-packages/torch/distributed/launch.py", line 196, in <module>
    main()
  File "/home/y/miniconda3/envs/Beit3/lib/python3.9/site-packages/torch/distributed/launch.py", line 192, in main
    launch(args)
  File "/home/y/miniconda3/envs/Beit3/lib/python3.9/site-packages/torch/distributed/launch.py", line 177, in launch
    run(args)
  File "/home/y/miniconda3/envs/Beit3/lib/python3.9/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/home/y/miniconda3/envs/Beit3/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/y/miniconda3/envs/Beit3/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 

**Please tell me what I should do to finetune successfully**

**Comment by jinqin-99** [comment]
Why the image_id in  submit_coco_captioning_val_e0.json  not equal with that in coco_karpathy_val_gt.json ?

**Comment by papersuper** [comment]
do you solve this problem？ i have the same question

**Comment by jinqin-99** [comment]
you&nbsp; can see this code&nbsp;pycocoevalcap/example/coco_eval_example.py at master · salaniz/pycocoevalcap (github.com)&nbsp;I just add&nbsp;coco_eval.params['image_id'] = coco_result.getImgIds() when val




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月10日(星期五) 下午3:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [microsoft/unilm] [Beit3] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 65181 closing signal SIGTERM. (Issue #1351)





 
do you solve this problem？ i have the same question

**Comment by papersuper** [comment]
Thank you for your response. I would like to ask, how was this issue resolved?
Traceback (most recent call last):
  File "/home/mengqiu/unilm-master/beit3/run_beit3_finetuning.py", line 448, in <module>
    main(opts, ds_init)
  File "/home/mengqiu/unilm-master/beit3/run_beit3_finetuning.py", line 317, in main
    model, optimizer, _, _ = ds_init(
  File "/storeData/USER/software/mq/anaconda3/envs/beit/lib/python3.9/site-packages/deepspeed/__init__.py", line 126, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/storeData/USER/software/mq/anaconda3/envs/beit/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 187, in __init__
Traceback (most recent call last):
  File "/home/mengqiu/unilm-master/beit3/run_beit3_finetuning.py", line 448, in <module>
    main(opts, ds_init)
  File "/home/mengqiu/unilm-master/beit3/run_beit3_finetuning.py", line 317, in main
    model, optimizer, _, _ = ds_init(
  File "/storeData/USER/software/mq/anaconda3/envs/beit/lib/python3.9/site-packages/deepspeed/__init__.py", line 126, in initialize
        engine = DeepSpeedEngine(args=args,self._configure_optimizer(optimizer, model_parameters)

  File "/storeData/USER/software/mq/anaconda3/envs/beit/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 689, in _configure_optimizer
  File "/storeData/USER/software/mq/anaconda3/envs/beit/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 187, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/storeData/USER/software/mq/anaconda3/envs/beit/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 689, in _configure_optimizer
    basic_optimizer = self._configure_basic_optimizer(model_parameters)
  File "/storeData/USER/software/mq/anaconda3/envs/beit/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 763, in _configure_basic_optimizer
    basic_optimizer = self._configure_basic_optimizer(model_parameters)
  File "/storeData/USER/software/mq/anaconda3/envs/beit/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 763, in _configure_basic_optimizer
    optimizer = FusedAdam(model_parameters,
  File "/storeData/USER/software/mq/anaconda3/envs/beit/lib/python3.9/site-packages/deepspeed/ops/adam/fused_adam.py", line 72, in __init__
    fused_adam_cuda = FusedAdamBuilder().load()
  File "/storeData/USER/software/mq/anaconda3/envs/beit/lib/python3.9/site-packages/deepspeed/ops/op_builder/builder.py", line 233, in load
    optimizer = FusedAdam(model_parameters,
  File "/storeData/USER/software/mq/anaconda3/envs/beit/lib/python3.9/site-packages/deepspeed/ops/adam/fused_adam.py", line 72, in __init__
    fused_adam_cuda = FusedAdamBuilder().load()
  File "/storeData/USER/software/mq/anaconda3/envs/beit/lib/python3.9/site-packages/deepspeed/ops/op_builder/builder.py", line 233, in load
    return self.jit_load(verbose)
  File "/storeData/USER/software/mq/anaconda3/envs/beit/lib/python3.9/site-packages/deepspeed/ops/op_builder/builder.py", line 248, in jit_load
    assert_no_cuda_mismatch()
  File "/storeData/USER/software/mq/anaconda3/envs/beit/lib/python3.9/site-packages/deepspeed/ops/op_builder/builder.py", line 77, in assert_no_cuda_mismatch
    return self.jit_load(verbose)
  File "/storeData/USER/software/mq/anaconda3/envs/beit/lib/python3.9/site-packages/deepspeed/ops/op_builder/builder.py", line 248, in jit_load
    raise Exception(
Exception: Installed CUDA version 11.6 does not match the version torch was compiled with 11.3, unable to compile cuda/cpp extensions without a matching cuda version.
    assert_no_cuda_mismatch()
  File "/storeData/USER/software/mq/anaconda3/envs/beit/lib/python3.9/site-packages/deepspeed/ops/op_builder/builder.py", line 77, in assert_no_cuda_mismatch
    raise Exception(
Exception: Installed CUDA version 11.6 does not match the version torch was compiled with 11.3, unable to compile cuda/cpp extensions without a matching cuda version.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 42763) of binary: /storeData/USER/software/mq/anaconda3/envs/beit/bin/python
Traceback (most recent call last):
  File "/storeData/USER/software/mq/anaconda3/envs/beit/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/storeData/USER/software/mq/anaconda3/envs/beit/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/storeData/USER/software/mq/anaconda3/envs/beit/lib/python3.9/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/storeData/USER/software/mq/anaconda3/envs/beit/lib/python3.9/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/storeData/USER/software/mq/anaconda3/envs/beit/lib/python3.9/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/storeData/USER/software/mq/anaconda3/envs/beit/lib/python3.9/site-packages/torch/distributed/run.py", line 710, in run
    elastic_launch(
  File "/storeData/USER/software/mq/anaconda3/envs/beit/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/storeData/USER/software/mq/anaconda3/envs/beit/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 259, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
run_beit3_finetuning.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-11-13_10:30:19
  host      : gpu01
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 42764)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-11-13_10:30:19
  host      : gpu01
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 42763)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

**Comment by kily-wmz** [comment]
I also encountered the same issue! Your solution is very effective, thank you very much.
