### ISSUE TITLE
ValueError: 'layoutlmv3' is already used by a Transformers config, pick another name.

### ISSUE THREAD

**Issue by AbdulDD** [microsoft/unilm#1354]
I am trying to fine tune Layout LM v3 on my custom data for document layout analysis (distinguishing between text, table and figure). but I am encountering following issue:

Traceback (most recent call last):
  File "/content/unilm/layoutlmv3/examples/object_detection/train_net.py", line 27, in <module>
    from ditod import add_vit_config
  File "/content/unilm/layoutlmv3/examples/object_detection/ditod/__init__.py", line 11, in <module>
    from .backbone import build_vit_fpn_backbone
  File "/content/unilm/layoutlmv3/examples/object_detection/ditod/backbone.py", line 29, in <module>
    from layoutlmft.models.layoutlmv3 import LayoutLMv3Model
  File "/content/unilm/layoutlmv3/layoutlmft/__init__.py", line 1, in <module>
    from .models import (
  File "/content/unilm/layoutlmv3/layoutlmft/models/__init__.py", line 1, in <module>
    from .layoutlmv3 import (
  File "/content/unilm/layoutlmv3/layoutlmft/models/layoutlmv3/__init__.py", line 16, in <module>
    AutoConfig.register("layoutlmv3", LayoutLMv3Config)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/configuration_auto.py", line 1094, in register
    CONFIG_MAPPING.register(model_type, config, exist_ok=exist_ok)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/configuration_auto.py", line 794, in register
    raise ValueError(f"'{key}' is already used by a Transformers config, pick another name.")
ValueError: 'layoutlmv3' is already used by a Transformers config, pick another name.

**Comment by hopegithub** [comment]
我也遇到同样的问题，请问你是怎么解决的呢

**Comment by huichentt** [comment]
Change the transformer version based on the [requirements.txt](https://github.com/microsoft/unilm/blob/master/layoutlmv3/requirements.txt) file: transformers==4.12.5.

**Comment by dreamlychina** [comment]
> 我也遇到同样的问题，请问你是怎么解决的呢

请问下你解决了？
