### ISSUE TITLE
RuntimeError: CUDA out of memory

### ISSUE THREAD

**Issue by andrewcby** [microsoft/unilm#137]
I’m having some CUDA out of memory error. I’m trying to train a network, but it seems the majority of the GPU is “reserved by PyTorch”. Here’s the error message: RuntimeError: `CUDA out of memory. Tried to allocate 128.00 MiB (GPU 0; 11.17 GiB total capacity; 10.85 GiB already allocated; 24.81 MiB free; 10.86 GiB reserved in total by PyTorch)`

I have tried using batch size 1, and it SOMETIMES work. But anything larger than 1 wouldn't work. Also here's my GPU info:
![Screen Shot 2020-05-15 at 9 10 27 AM](https://user-images.githubusercontent.com/6632338/82007403-b68d4e80-969c-11ea-984a-cabda0e4f84c.png)

It might have to do with how unilm is doing memory management?

**Comment by donglixp** [comment]
Hi @andrewcby . Could you provide more details about the OOM message (such as the command)?

**Comment by andrewcby** [comment]
Hi @donglixp, 
My code to run the training is as follow: 
```
python run_classification.py  --data_dir  ../../data \
                              --model_type layoutlm \
                              --model_name_or_path ../../layoutLM \
                              --output_dir /dbfs/FileStore/LayoutLMOutput2 \
                              --do_lower_case \
                              --max_seq_length 512 \
                              --task_name cdip \
                              --do_train \
                              --do_eval \
                              --num_train_epochs 10.0 \
                              --logging_steps 5000 \
                              --save_steps 5000 \
                              --per_gpu_train_batch_size 8 \
                              --per_gpu_eval_batch_size 8 \
                              --evaluate_during_training \
                              --fp16 
```
And the error message is here:
```
05/15/2020 06:31:01 - WARNING - __main__ -   Process rank: -1, device: cuda:0, n_gpu: 1, distributed training: False, 16-bits training: True
05/15/2020 06:31:01 - INFO - transformers.configuration_utils -   loading configuration file ../../layoutLM/config.json
05/15/2020 06:31:01 - INFO - transformers.configuration_utils -   Model config BertConfig {
  "attention_probs_dropout_prob": 0.1,
  "finetuning_task": "cdip",
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 1024,
  "id2label": {
    "0": "LABEL_0",
    "1": "LABEL_1",
    "2": "LABEL_2",
    "3": "LABEL_3",
    ...
    "162": "LABEL_162"
  },
  "initializer_range": 0.02,
  "intermediate_size": 4096,
  "label2id": {
    "LABEL_0": 0,
    "LABEL_1": 1,
    "LABEL_10": 10,
    ...
    "LABEL_99": 99
  },
  "layer_norm_eps": 1e-12,
  "max_2d_position_embeddings": 1024,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "output_past": true,
  "pad_token_id": 0,
  "type_vocab_size": 2,
  "vocab_size": 30522
}

05/15/2020 06:31:01 - INFO - transformers.tokenization_utils -   Model name '../../layoutLM' not found in model shortcut name list (bert-base-uncased, bert-large-uncased, bert-base-cased, bert-large-cased, bert-base-multilingual-uncased, bert-base-multilingual-cased, bert-base-chinese, bert-base-german-cased, bert-large-uncased-whole-word-masking, bert-large-cased-whole-word-masking, bert-large-uncased-whole-word-masking-finetuned-squad, bert-large-cased-whole-word-masking-finetuned-squad, bert-base-cased-finetuned-mrpc, bert-base-german-dbmdz-cased, bert-base-german-dbmdz-uncased, bert-base-finnish-cased-v1, bert-base-finnish-uncased-v1, bert-base-dutch-cased). Assuming '../../layoutLM' is a path, a model identifier, or url to a directory containing tokenizer files.
05/15/2020 06:31:01 - INFO - transformers.tokenization_utils -   loading file ../../layoutLM/vocab.txt
05/15/2020 06:31:01 - INFO - transformers.tokenization_utils -   loading file ../../layoutLM/added_tokens.json
05/15/2020 06:31:01 - INFO - transformers.tokenization_utils -   loading file ../../layoutLM/special_tokens_map.json
05/15/2020 06:31:01 - INFO - transformers.tokenization_utils -   loading file ../../layoutLM/tokenizer_config.json
05/15/2020 06:31:01 - INFO - transformers.modeling_utils -   loading weights file ../../layoutLM/pytorch_model.bin
05/15/2020 06:31:10 - INFO - transformers.modeling_utils -   Weights of LayoutLMForSequenceClassification not initialized from pretrained model: ['classifier.weight', 'classifier.bias']
05/15/2020 06:31:10 - INFO - transformers.modeling_utils -   Weights from pretrained model not used in LayoutLMForSequenceClassification: ['cls.predictions.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.decoder.weight']
05/15/2020 06:31:12 - INFO - __main__ -   Training/evaluation parameters Namespace(adam_epsilon=1e-08, cache_dir='', config_name='', data_dir='../../data', device=device(type='cuda', index=0), do_eval=True, do_lower_case=True, do_train=True, eval_all_checkpoints=False, evaluate_during_training=True, fp16=True, fp16_opt_level='O1', gradient_accumulation_steps=1, hierarchical_tokens=False, learning_rate=5e-05, local_rank=-1, logging_steps=5000, max_grad_norm=1.0, max_seq_length=512, max_steps=-1, model_name_or_path='../../layoutLM', model_type='layoutlm', n_gpu=1, no_cuda=False, num_train_epochs=10.0, output_dir='/dbfs/FileStore/LayoutLMOutput2', output_mode='classification', overwrite_cache=False, overwrite_output_dir=False, per_gpu_eval_batch_size=8, per_gpu_train_batch_size=8, save_steps=5000, seed=42, server_ip='', server_port='', task_name='cdip', tokenizer_name='', tpu=False, tpu_ip_address='', tpu_name='', warmup_steps=0, weight_decay=0.0, xrt_tpu_config='')
05/15/2020 06:31:12 - INFO - __main__ -   Loading features from cached file ../../data/cached_train_layoutLM_512_cdip
05/15/2020 06:31:13 - INFO - __main__ -   ***** Running training *****
05/15/2020 06:31:13 - INFO - __main__ -     Num examples = 999
05/15/2020 06:31:13 - INFO - __main__ -     Num Epochs = 10
05/15/2020 06:31:13 - INFO - __main__ -     Instantaneous batch size per GPU = 8
05/15/2020 06:31:13 - INFO - __main__ -     Total train batch size (w. parallel, distributed & accumulation) = 8
05/15/2020 06:31:13 - INFO - __main__ -     Gradient Accumulation steps = 1
05/15/2020 06:31:13 - INFO - __main__ -     Total optimization steps = 1250

Epoch:   0%|          | 0/10 [00:00<?, ?it/s]

Iteration:   0%|          | 0/125 [00:00<?, ?it/s]Selected optimization level O1:  Insert automatic casts around Pytorch functions and Tensor methods.

Defaults for this optimization level are:
enabled                : True
opt_level              : O1
cast_model_type        : None
patch_torch_functions  : True
keep_batchnorm_fp32    : None
master_weights         : None
loss_scale             : dynamic
Processing user overrides (additional kwargs that are not None)...
After processing overrides, optimization options are:
enabled                : True
opt_level              : O1
cast_model_type        : None
patch_torch_functions  : True
keep_batchnorm_fp32    : None
master_weights         : None
loss_scale             : dynamic
Traceback (most recent call last):
  File "run_classification.py", line 860, in <module>
    main()
  File "run_classification.py", line 794, in main
    global_step, tr_loss = train(args, train_dataset, model, tokenizer)
  File "run_classification.py", line 216, in train
    outputs = model(**inputs)
  File "/databricks/conda/envs/databricks-ml-gpu/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/databricks/driver/unilm/layoutlm/modeling_layoutlm.py", line 330, in forward
    head_mask=head_mask,
  File "/databricks/conda/envs/databricks-ml-gpu/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/databricks/driver/unilm/layoutlm/modeling_layoutlm.py", line 193, in forward
    embedding_output, extended_attention_mask, head_mask=head_mask
  File "/databricks/conda/envs/databricks-ml-gpu/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/databricks/conda/envs/databricks-ml-gpu/lib/python3.7/site-packages/transformers/modeling_bert.py", line 407, in forward
    hidden_states, attention_mask, head_mask[i], encoder_hidden_states, encoder_attention_mask
  File "/databricks/conda/envs/databricks-ml-gpu/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/databricks/conda/envs/databricks-ml-gpu/lib/python3.7/site-packages/transformers/modeling_bert.py", line 368, in forward
    self_attention_outputs = self.attention(hidden_states, attention_mask, head_mask)
  File "/databricks/conda/envs/databricks-ml-gpu/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/databricks/conda/envs/databricks-ml-gpu/lib/python3.7/site-packages/transformers/modeling_bert.py", line 314, in forward
    hidden_states, attention_mask, head_mask, encoder_hidden_states, encoder_attention_mask
  File "/databricks/conda/envs/databricks-ml-gpu/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/databricks/conda/envs/databricks-ml-gpu/lib/python3.7/site-packages/transformers/modeling_bert.py", line 251, in forward
    context_layer = torch.matmul(attention_probs, value_layer)
  File "/databricks/conda/envs/databricks-ml-gpu/lib/python3.7/site-packages/apex/amp/wrap.py", line 27, in wrapper
    kwargs)
  File "/databricks/conda/envs/databricks-ml-gpu/lib/python3.7/site-packages/apex/amp/utils.py", line 81, in casted_args
    new_args.append(cast_fn(x))
  File "/databricks/conda/envs/databricks-ml-gpu/lib/python3.7/site-packages/apex/amp/utils.py", line 63, in maybe_half
    return x.half()
RuntimeError: CUDA out of memory. Tried to allocate 64.00 MiB (GPU 0; 11.17 GiB total capacity; 10.82 GiB already allocated; 56.81 MiB free; 10.83 GiB reserved in total by PyTorch)
```

**Comment by andrewcby** [comment]
Update: 
I managed to resolve the issue. Though this is not a perfect fix. What I did is I shortened the `--max_seq_length 512` option from 512 to 128. This parameter is for BERT sequence length, and it's the number of *token*, or in other words, words. So unless you are dealing with a dataset of images with high text density, you do not need that long of a sequence. There are a few papers and videos on this that I cannot remember on top of my head but they also suggested using shorter sequence (128 or 64) and getting more robust performance. With this modification, I'm able to run training with 16 batch size. After around 11 hours of training on a GPU cluster, I got 96% accuracy on 163 classes dataset with a total of over 19k pages. Please note this is very good result as some of the classes have single digit number of samples and therefore hard to learn well.

**Comment by wolfshow** [comment]
@andrewcby thanks for the updates! Did you try reducing the batch size and still use 512 as the maximum length?

**Comment by andrewcby** [comment]
@wolfshow with max length 512, only batch size = 1 works *sometimes*. If I stop the process and start again, without restarting the cluster, I would get the CUDA error.. I think pytorch is notorious for bad memory management. I noticed there are some `with no_grad` in your code already, but I guess pytorch is still hogging a lot of memory.

**Comment by wolfshow** [comment]
@andrewcby It seems that the K80 GPU only has 12GB memory, which is a little small for the fine-tuning. It is better to try a different GPU with at least 16GB memory and it will work well.

**Comment by mfxss** [comment]
> @andrewcby It seems that the K80 GPU only has 12GB memory, which is a little small for the fine-tuning. It is better to try a different GPU with at least 16GB memory and it will work well.

I am using a larger GPU with 24GB but still got the same issue.

**Comment by andrewcby** [comment]
> > @andrewcby It seems that the K80 GPU only has 12GB memory, which is a little small for the fine-tuning. It is better to try a different GPU with at least 16GB memory and it will work well.
> 
> I am using a larger GPU with 24GB but still got the same issue.

Try with a smaller batch size. It helped me since it's not possible for me to get a larger GPU

**Comment by mfxss** [comment]
> > > @andrewcby It seems that the K80 GPU only has 12GB memory, which is a little small for the fine-tuning. It is better to try a different GPU with at least 16GB memory and it will work well.
> > 
> > 
> > I am using a larger GPU with 24GB but still got the same issue.
> 
> Try with a smaller batch size. It helped me since it's not possible for me to get a larger GPU

Yeah，it worked when batch is 8.
