### ISSUE TITLE
For TextDiffuser-2 inpainting

### ISSUE THREAD

**Issue by ada-powerful** [microsoft/unilm#1418]
**Describe the bug**
textdiffuser-2's inpainting demo does not work.

The problem arises when using:
* [x] the official example scripts: 

python ./demo_textdiffuser2_inpainting_full.py

**To Reproduce**
1. cd textdiffuser-2
2. python ./demo_textdiffuser2_inpainting_full.py
3. On the gradio console, specify the mask and click generate 
4. I got error:

Traceback (most recent call last):
  File "/home/tq/anaconda3/envs/textdiffuser2/lib/python3.8/site-packages/gradio/routes.py", line 534, in predict
    output = await route_utils.call_process_api(
  File "/home/tq/anaconda3/envs/textdiffuser2/lib/python3.8/site-packages/gradio/route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/tq/anaconda3/envs/textdiffuser2/lib/python3.8/site-packages/gradio/blocks.py", line 1550, in process_api
    result = await self.call_function(
  File "/home/tq/anaconda3/envs/textdiffuser2/lib/python3.8/site-packages/gradio/blocks.py", line 1185, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/tq/anaconda3/envs/textdiffuser2/lib/python3.8/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/home/tq/anaconda3/envs/textdiffuser2/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
  File "/home/tq/anaconda3/envs/textdiffuser2/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "/home/tq/anaconda3/envs/textdiffuser2/lib/python3.8/site-packages/gradio/utils.py", line 661, in wrapper
    response = f(*args, **kwargs)
  File "./demo_textdiffuser2_inpainting_full.py", line 549, in text_to_image
    noise_pred_cond = unet(sample=input, timestep=t, encoder_hidden_states=encoder_hidden_states_cond[:slider_batch],feature_mask=feature_mask, masked_feature=masked_feature).sample # b, 4, 64, 64
  File "/home/tq/anaconda3/envs/textdiffuser2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/tq/anaconda3/envs/textdiffuser2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
TypeError: forward() got an unexpected keyword argument 'feature_mask'

- Platform:
- Python version: 3.8
- PyTorch version (GPU?): 2.1.2+cu121 (cuda: 12.2)

**Comment by JingyeChen** [comment]
For training the text inpainting task, please install the diffusers package using the command pip install https://github.com/JingyeChen/diffusers_td2.git. Note that the U-Net architecture has been modified for receiving more input features.

**Comment by ada-powerful** [comment]
> For training the text inpainting task, please install the diffusers package using the command pip install https://github.com/JingyeChen/diffusers_td2.git. Note that the U-Net architecture has been modified for receiving more input features.

Thanks! That finally worked.
