### ISSUE TITLE
demo_textdiffuser2_inpainting_full.py can't load checkpoints

### ISSUE THREAD

**Issue by loliq** [microsoft/unilm#1425]
**Describe the bug**
Model I am using (UniLM, MiniLM, LayoutLM ...):

The problem arises when using:
- [x]  the official example scripts: `demo_textdiffuser2_inpainting_full.py`

**To Reproduce**
1.   When I loaded pretrained model `textdiffuser2-full-ft-inpainting` (which is downloaded from https://huggingface.co/JingyeChen22/textdiffuser2-full-ft-inpainting ) from my disk ,   I got an error: 

```
Traceback (most recent call last):
  File "/home/llluo3/miniconda3/envs/textdiffuser2/lib/python3.8/site-packages/transformers/modeling_utils.py", line 442, in load_state_dict
    return torch.load(checkpoint_file, map_location="cpu")
  File "/home/llluo3/miniconda3/envs/textdiffuser2/lib/python3.8/site-packages/torch/serialization.py", line 1028, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/llluo3/miniconda3/envs/textdiffuser2/lib/python3.8/site-packages/torch/serialization.py", line 1246, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: unpickling stack underflow

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/llluo3/miniconda3/envs/textdiffuser2/lib/python3.8/site-packages/transformers/modeling_utils.py", line 446, in load_state_dict
    if f.read(7) == "version":
  File "/home/llluo3/miniconda3/envs/textdiffuser2/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x87 in position 0: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "demo_textdiffuser2_inpainting_full.py", line 38, in <module>
    text_encoder = CLIPTextModel.from_pretrained(
  File "/home/llluo3/miniconda3/envs/textdiffuser2/lib/python3.8/site-packages/transformers/modeling_utils.py", line 2560, in from_pretrained
    state_dict = load_state_dict(resolved_archive_file)
  File "/home/llluo3/miniconda3/envs/textdiffuser2/lib/python3.8/site-packages/transformers/modeling_utils.py", line 458, in load_state_dict
    raise OSError(
OSError: Unable to load weights from pytorch checkpoint file for '/mnt/disk_10T/ubuntu_file/llluo3/Checkpoints/HuggingFace/textdiffuser2-full-ft-inpainting/text_encoder/pytorch_model.bin' at '/mnt/disk_10T/ubuntu_file/llluo3/Checkpoints/HuggingFace/textdiffuser2-full-ft-inpainting/text_encoder/pytorch_model.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.
```
- Platform: ubuntu 22.04
- Python version: 3.8 
- PyTorch version (GPU): 2.1.2-GPU

**Comment by JingyeChen** [comment]
Hi, thanks for your interest in TextDiffuser-2. What is the version of transformers? Maybe you can try transformers==4.28.1

**Comment by loliq** [comment]
> Hi, thanks for your interest in TextDiffuser-2. What is the version of transformers? Maybe you can try transformers==4.28.1

Thanks for replying. I solved it by downloading the checkpoints again ^-^
