### ISSUE TITLE
RuntimeError: Expected object of device type cuda but got device type cpu for argument #3 'index' in call to _th_index_select

### ISSUE THREAD

**Issue by nv-quan** [microsoft/unilm#160]
**Describe the bug**
Model I am using: LayoutLM

The problem arises when using:
* [x] the official example scripts: run_seq_labeling
* [ ] my own modified scripts: (give details below)

**To Reproduce**
1. Training with old version (commit 769852eb3ea40693f40584b7dc5a4910cc57a495) has no problem
2. Install apex, pull [new version](https://github.com/microsoft/unilm/commit/a21ac4a893e44440674123ae63fd9c6f9b67a82d) from master, install as instructed in README.md, download dataset
3. Run preprocess.sh
4. Run run_seq_labeling.py with all the options provided in README.md
5. Confirm cuda is available

**Expected behavior**
This error happened:
```
Selected optimization level O1:  Insert automatic casts around Pytorch functions and Tensor methods.

Defaults for this optimization level are:
enabled                : True
opt_level              : O1
cast_model_type        : None
patch_torch_functions  : True
keep_batchnorm_fp32    : None
master_weights         : None
loss_scale             : dynamic
Processing user overrides (additional kwargs that are not None)...
After processing overrides, optimization options are:
enabled                : True
opt_level              : O1
cast_model_type        : None
patch_torch_functions  : True
keep_batchnorm_fp32    : None
master_weights         : None
loss_scale             : dynamic
Warning:  multi_tensor_applier fused unscale kernel is unavailable, possibly because apex was installed without --cuda_ext --cpp_ext. Using Python fallback.  Original ImportError was: ModuleNotFoundError("No module named 'amp_C'",)
Traceback (most recent call last):
  File "run_seq_labeling.py", line 811, in <module>
    main()
  File "run_seq_labeling.py", line 704, in main
    args, train_dataset, model, tokenizer, labels, pad_token_label_id
  File "run_seq_labeling.py", line 219, in train
    outputs = model(**inputs)
  File "/home/ubuntu/anaconda3/envs/layoutlm/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/layoutlm/lib/python3.6/site-packages/layoutlm/modeling/layoutlm.py", line 217, in forward
    head_mask=head_mask,
  File "/home/ubuntu/anaconda3/envs/layoutlm/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/layoutlm/lib/python3.6/site-packages/layoutlm/modeling/layoutlm.py", line 171, in forward
    input_ids, bbox, position_ids=position_ids, token_type_ids=token_type_ids
  File "/home/ubuntu/anaconda3/envs/layoutlm/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/layoutlm/lib/python3.6/site-packages/layoutlm/modeling/layoutlm.py", line 84, in forward
    token_type_embeddings = self.token_type_embeddings(token_type_ids)
  File "/home/ubuntu/anaconda3/envs/layoutlm/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/layoutlm/lib/python3.6/site-packages/torch/nn/modules/sparse.py", line 114, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "/home/ubuntu/anaconda3/envs/layoutlm/lib/python3.6/site-packages/torch/nn/functional.py", line 1484, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected object of device type cuda but got device type cpu for argument #3 'index' in call to _th_index_select
```

- Platform: Ubuntu 18.04
- Python version: Python 3.6.10
- PyTorch version (GPU?): 1.4.0

**Comment by ranpox** [comment]
Hi @nv-quan , 
Thanks for your feedback. I have updated the example code. Please pull the latest code and try again. Thanks.

**Comment by nv-quan** [comment]
It seems to be ok but do you get this warning?
```
Warning:  multi_tensor_applier fused unscale kernel is unavailable, possibly because apex was installed without --cuda_ext --cpp_ext. Using Python fallback.  Original Import
Error was: ModuleNotFoundError("No module named 'amp_C'",)
Epoch:   0%|                                                  | 0/100 [00:00<?, ?it/sGradient overflow.  Skipping step, loss scaler 0 reducing loss scale to 32768.0, ?it/s]
/home/ubuntu/anaconda3/envs/layoutlm/lib/python3.6/site-packages/torch/optim/lr_scheduler.py:113: UserWarning: Seems like `optimizer.step()` has been overridden after learni
ng rate scheduler initialization. Please, make sure to call `optimizer.step()` before `lr_scheduler.step()`. See more details at https://pytorch.org/docs/stable/optim.html#h
ow-to-adjust-learning-rate
  "https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate", UserWarning)
                                                                                     /home/ubuntu/anaconda3/envs/layoutlm/lib/python3.6/site-packages/torch/optim/lr_schedule
r.py:224: UserWarning: To get the last learning rate computed by the scheduler, please use `get_last_lr()`.
  warnings.warn("To get the last learning rate computed by the scheduler, "
```

**Comment by ranpox** [comment]
Please install apex with CUDA and C++ extensions. Also, please make sure that you have rebuilt apex again after upgrading PyTorch.

**Comment by nv-quan** [comment]
After rebuild apex I couldn't event import it, but I think that's a bug of apex instead of unilm. Thank you.
