### ISSUE TITLE
[LayoutLM] RuntimeError cudaErrorIllegalAddress

### ISSUE THREAD

**Issue by renjithsasidharan** [microsoft/unilm#162]
**Describe the bug**
Model I am using (UniLM, MiniLM, LayoutLM ...): LayoutLM

The problem arises when using:
* [ ] the official example scripts: (give details below)
* [x] my own modified scripts: (give details below)
Just Fine-tuning on custom dataset.

Fine-tune the sequence label model on single GPU by setting `--max_seq_length` to 768. The training crashes.

**To Reproduce**
1. Fine-tune sequence label the model setting `--max_seq_length` to 768
```sh
!python examples/seq_labeling/run_seq_labeling.py  --data_dir ./er_data \
                            --model_type layoutlm \
                            --model_name_or_path layoutlm-base-uncased \
                            --do_lower_case \
                            --max_seq_length 768 \
                            --do_train \
                            --num_train_epochs 2.0 \
                            --logging_steps 10 \
                            --save_steps -1 \
                            --output_dir output \
                            --labels ./er_data/labels.txt \
                            --per_gpu_train_batch_size 8 \
                            --fp16 \
                            --evaluate_during_training
```

```
Iteration:   0% 1/3016 [00:00<38:44,  1.30it/s]Gradient overflow.  Skipping step, loss scaler 0 reducing loss scale to 16384.0

Iteration:   0% 2/3016 [00:01<38:24,  1.31it/s]Traceback (most recent call last):
  File "examples/seq_labeling/run_seq_labeling.py", line 823, in <module>
    main()
  File "examples/seq_labeling/run_seq_labeling.py", line 716, in main
    args, train_dataset, model, tokenizer, labels, pad_token_label_id
  File "examples/seq_labeling/run_seq_labeling.py", line 233, in train
    scaled_loss.backward()
  File "/usr/local/lib/python3.6/dist-packages/torch/tensor.py", line 198, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/__init__.py", line 100, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: transform: failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered
```

**Expected behavior**

- Platform: Google Colab
- Python version: 3.6
- PyTorch version (GPU?):1.5.0+cu101

**Comment by ranpox** [comment]
Hi @renjithsasidharan , 
The maximum sequence length of LayoutLM is 512.
