### ISSUE TITLE
Assertion `srcIndex < srcSelectDimSize` failed when fine tuning seq_labeling with custom dataset

### ISSUE THREAD

**Issue by nv-quan** [microsoft/unilm#164]
**Describe**
I'm running fine tuning seq_labeling (not modified) code with my own dataset. I've tried to make my dataset look similar to FUNSD but still encounter this error. Do you have any idea about what could go wrong? Any suggestions is appreciated. Thank you very much.
```
/opt/conda/conda-bld/pytorch_1579022034529/work/aten/src/THC/THCTensorIndex.cu:361: void indexSelectLargeIndex(TensorInfo<T,r IndexType>, TensorInfo<T, IndexType>, TensorInfo
<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = -1, SrcDim = -1, IdxDim = -1, IndexIsMajor = true]: block: [128,
0,0], thread: [63,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
Traceback (most recent call last):                                                                                                                                   [7/1026]
  File "run_seq_labeling.py", line 811, in <module>                                                                                                                          
    main()                                                                                                                                                                   
  File "run_seq_labeling.py", line 704, in main                                                                                                                              
    args, train_dataset, model, tokenizer, labels, pad_token_label_id                                                                                                        
  File "run_seq_labeling.py", line 219, in train                                                                             
    outputs = model(**inputs)                                                                                                      
  File "/home/ubuntu/anaconda3/envs/layoutlm/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/layoutlm/lib/python3.6/site-packages/layoutlm/modeling/layoutlm.py", line 217, in forward
    head_mask=head_mask,                         
  File "/home/ubuntu/anaconda3/envs/layoutlm/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/layoutlm/lib/python3.6/site-packages/layoutlm/modeling/layoutlm.py", line 174, in forward
    embedding_output, extended_attention_mask, head_mask=head_mask
  File "/home/ubuntu/anaconda3/envs/layoutlm/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/layoutlm/lib/python3.6/site-packages/transformers/modeling_bert.py", line 407, in forward
    hidden_states, attention_mask, head_mask[i], encoder_hidden_states, encoder_attention_mask
  File "/home/ubuntu/anaconda3/envs/layoutlm/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/layoutlm/lib/python3.6/site-packages/transformers/modeling_bert.py", line 368, in forward
    self_attention_outputs = self.attention(hidden_states, attention_mask, head_mask)   
  File "/home/ubuntu/anaconda3/envs/layoutlm/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__                                      
    result = self.forward(*input, **kwargs)                                                                                                                  
  File "/home/ubuntu/anaconda3/envs/layoutlm/lib/python3.6/site-packages/transformers/modeling_bert.py", line 314, in forward
    hidden_states, attention_mask, head_mask, encoder_hidden_states, encoder_attention_mask                                        
  File "/home/ubuntu/anaconda3/envs/layoutlm/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/layoutlm/lib/python3.6/site-packages/transformers/modeling_bert.py", line 216, in forward
    mixed_query_layer = self.query(hidden_states)
  File "/home/ubuntu/anaconda3/envs/layoutlm/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/layoutlm/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 87, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/ubuntu/anaconda3/envs/layoutlm/lib/python3.6/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/layoutlm/lib/python3.6/site-packages/torch/nn/functional.py", line 1372, in linear
    output = input.matmul(weight.t())
  File "/home/ubuntu/anaconda3/envs/layoutlm/lib/python3.6/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`
```

**Comment by nv-quan** [comment]
I've figured it out, my data causes index out of bound somewhere. I can only see the problem when use the --no_cuda option, which gives more accurate error.

**Comment by victor-ab** [comment]
@nv-quan, do you how exactly did you fix this?
I got the same problem, but I don't know what is out of range in my data.

**Comment by nv-quan** [comment]
> @nv-quan, do you how exactly did you fix this?
> I got the same problem, but I don't know what is out of range in my data.

I tried with the --no_cuda option and it gives me some clue to trace back to the cause of the error.

**Comment by shreyaschim** [comment]
, Hi Everyone!
 I was also facing the same issue with my embedding for customize dataset, 
`

> opt/conda/conda-bld/pytorch_1579022060824/work/aten/src/THC/THCTensorIndex.cu:361: void indexSelectLargeIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = -1, SrcDim = -1, IdxDim = -1, IndexIsMajor = true]: block: [32,0,0], thread: [23,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

`

So I pass the --no_cuda option as mention by @nv-quan ,
which shows me following error,

> Error was :  " index out of range: Tried to access index 1106 out of table with 1023 rows. pytorch image src"

It was due to wrong assignment of  values, actually I had assigned height in place of width and width in place of height.
I know it is very silly mistake but, this can be a case that's why posting it.  
This solved my problem,
Thank you...
