### ISSUE TITLE
Missing LayoutlmConfig file in LayoutLm folder

### ISSUE THREAD

**Issue by shubhangi27397** [microsoft/unilm#167]
**Describe**
The model I am using LayoutLM: I want to check the predictions of pre-trained models but unable to run run_classification.py for document classification
ERROR --- 
Traceback (most recent call last):
  File "run_classification.py", line 27, in <module>
    from layoutlm import LayoutlmConfig, LayoutlmForSequenceClassification
ModuleNotFoundError: No module named 'layoutlm'

**Comment by nv-quan** [comment]
You should run `pip install .` at the layoutlm folder first.

**Comment by shubhangi27397** [comment]
> You should run `pip install .` at `unilm/layoutlm/` first.

Thank you so much for your help it worked

**Comment by shubhangi27397** [comment]
COuld you please explain me one more step in testing the pre -trained model.
When I run python script I get this error 
OSError: Error reading file 'D:\Document_structure\unilm-master\layoutlm\layoutlm\data\images\imagesi/i/b/f/ibf45f00/0060052794.xml': failed to load external entity "file:/D:/Document_structure/unilm-master/layoutlm/layoutlm/data/images/imagesi/i/b/f/ibf45f00/0060052794.xml"
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run_classification.py", line 723, in <module>
    main()
  File "run_classification.py", line 681, in main
    result = evaluate(args, model, tokenizer, mode="val", prefix=prefix)
  File "run_classification.py", line 269, in evaluate
    eval_dataset = load_and_cache_examples(args, tokenizer, mode=mode)
  File "C:\Users\shubhangi.ojha\AppData\Local\Continuum\anaconda3\envs\layoutlm\lib\site-packages\layoutlm\data\rvl_cdip.py", line 277, in load_and_cache_examples
    examples = processor.get_examples(args.data_dir, mode)
  File "C:\Users\shubhangi.ojha\AppData\Local\Continuum\anaconda3\envs\layoutlm\lib\site-packages\layoutlm\data\rvl_cdip.py", line 70, in get_examples
    for example in p.imap(self.worker, lines):
  File "C:\Users\shubhangi.ojha\AppData\Local\Continuum\anaconda3\envs\layoutlm\lib\multiprocessing\pool.py", line 735, in next
    raise value
OSError: Error reading file 'D:\Document_structure\unilm-master\layoutlm\layoutlm\data\images\imagesi/i/b/f/ibf45f00/0060052794.xml': failed to load external entity "file:/D:/Document_structure/unilm-master/layoutlm/layoutlm/data/images/imagesi/i/b/f/ibf45f00/0060052794.xml"

**Comment by jyotiyadav94** [comment]
I am still facing the above error 

Traceback (most recent call last):
  File "unilm\\layoutlm\\examples\\seq_labeling\\run_seq_labeling.py", line 53, in <module>
    from layoutlm import FunsdDataset, LayoutlmConfig, LayoutlmForTokenClassification
ImportError: cannot import name 'LayoutlmConfig' from 'layoutlm'
