### ISSUE TITLE
AttributeError: module 'apex.amp' has no attribute 'initialize'

### ISSUE THREAD

**Issue by fabrahman** [microsoft/unilm#172]
Hi,

I am running the following command to fine-tune unilm-large on my dataset. However, it is throwing error on apex.amp.initialize.
I uninstalled and reinstalled apex several times but it didn't solve the problem. Also, I am following the nvidia github for installing apex.

command:
```
 python run_seq2seq.py   --train_file ${TRAIN_FILE} --output_dir ${OUTPUT_DIR}   --model_type unilm --model_name_or_path unilm1-large-cased --fp16 --fp16_opt_level 02 --max_source_seq_length 568 --max_target_seq_length 200 --per_gpu_train_batch_size 2 --gradient_accumulation_steps 1 --learning_rate 7e-5 --num_warmup_steps 500 --num_training_steps 32000 --cache_dir ${CACHE_DIR
```

error log:
```

06/08/2020 13:25:11 - INFO - transformers.tokenization_utils -   loading file https://unilm.blob.core.windows.net/ckpt/unilm1-large-cased-vocab.txt from cache at CACHE/8341229b5648bc2f7326c2bdc44da5967aee0f799dea420ba6cdce4aa6a68be6.c9846572e7bc47de74e4b6199339046a25fbd26dd5ff8fb0a3cbb748297b05d7
06/08/2020 13:25:11 - INFO - s2s_ft.convert_state_dict -   loading weights file https://unilm.blob.core.windows.net/ckpt/unilm1-large-cased.bin from cache at CACHE/a2f778ecb446c3792f3d8e6e4d576502f399771d91fa2a6602d54d541a409162.98783e0f602a3731fbb3b08c93e41ef883be023586fffdf5ec304ad1ddfcf31f
06/08/2020 13:25:11 - INFO - s2s_ft.modeling -   Resize > position embeddings !
/home/hannahbrahman/Char_Desc_Gen/unilm/s2s-ft/s2s_ft/modeling.py:122: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than tensor.new_tensor(sourceTensor).
  size=(config.max_position_embeddings, state_dict[_k].shape[1])), dtype=torch.float)
06/08/2020 13:25:12 - INFO - s2s_ft.modeling -     CP [0 ~ 512] into [0 ~ 512]
06/08/2020 13:25:12 - INFO - s2s_ft.modeling -     CP [0 ~ 256] into [512 ~ 768]
06/08/2020 13:25:12 - INFO - transformers.modeling_utils -   loading weights file https://unilm.blob.core.windows.net/ckpt/unilm1-large-cased.bin from cache at CACHE/a2f778ecb446c3792f3d8e6e4d576502f399771d91fa2a6602d54d541a409162.98783e0f602a3731fbb3b08c93e41ef883be023586fffdf5ec304ad1ddfcf31f
06/08/2020 13:25:15 - INFO - transformers.modeling_utils -   Weights of BertForSequenceToSequence not initialized from pretrained model: ['cls.predictions.decoder_weight', 'crit_mask_lm_smoothed.one_hot']
06/08/2020 13:25:15 - INFO - transformers.modeling_utils -   Weights from pretrained model not used in BertForSequenceToSequence: ['bert.pooler.dense.weight', 'bert.pooler.dense.bias', 'cls.seq_relationship.weight', 'cls.seq_relationship.bias', 'cls.predictions.decoder.weight']
06/08/2020 13:25:15 - INFO - s2s_ft.utils -   Loading features from cached file ./save_checkpoints/cached_features_for_training.pt
Traceback (most recent call last):
  File "run_seq2seq.py", line 421, in <module>
    main()
  File "run_seq2seq.py", line 417, in main
    train(args, training_features, model, tokenizer)
  File "run_seq2seq.py", line 107, in train
    model, optimizer = prepare_for_training(args, model, checkpoint_state_dict, amp=amp)
  File "run_seq2seq.py", line 58, in prepare_for_training
    model, optimizer = amp.initialize(model, optimizer, opt_level=args.fp16_opt_level) # old: initialize
AttributeError: module 'apex.amp' has no attribute 'initialize'
```

Do you have any thoughts on this issue?
Thanks

**Comment by addf400** [comment]
It looks like you have an old version of apex, you can try install a latest version of apex.
bash
```
git clone https://github.com/NVIDIA/apex.git && cd apex && python setup.py install --cuda_ext --cpp_ext

**Comment by donglixp** [comment]
The environment setup is described at https://github.com/microsoft/unilm/tree/master/s2s-ft#environment :

```bash
git clone https://github.com/NVIDIA/apex.git && cd apex && git reset --hard de6378f5dae8fcf2879a4be8ecea8bbcb9e59d5 && python setup.py install --cuda_ext --cpp_ext
```

The apex of the version `de6378f5dae8fcf2879a4be8ecea8bbcb9e59d5` can be used.
