### ISSUE TITLE
RuntimeError: CUDA out of memory. Tried to allocate 24.00 MiB (GPU 0; 3.95 GiB total capacity; 3.07 GiB already allocated; 20.31 MiB free; 3.09 GiB reserved in total by PyTorch)

### ISSUE THREAD

**Issue by shreyaschim** [microsoft/unilm#175]
```
Traceback (most recent call last):
  File "run_seq_labeling.py", line 811, in <module>
    main()
  File "run_seq_labeling.py", line 704, in main
    args, train_dataset, model, tokenizer, labels, pad_token_label_id
  File "run_seq_labeling.py", line 230, in train
    scaled_loss.backward()
  File "/home/shreyas/anaconda3/envs/layoutlm/lib/python3.6/site-packages/torch/tensor.py", line 195, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/shreyas/anaconda3/envs/layoutlm/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: CUDA out of memory. Tried to allocate 24.00 MiB (GPU 0; 3.95 GiB total capacity; 3.07 GiB already allocated; 20.31 MiB free; 3.09 GiB reserved in total by PyTorch)

```
Model I am using LayoutLM
Platform: ubuntu 18.04, GTX 1050, CUDA 10.1, PyTorch 1.4
I followed the exact steps given in the read section, "run_seq_labeling.py" continues giving me the above error. I have tried changing batch size, clearing pytorch cache but none of them work for me. 
Please guide me if anyone had encountered such issue before, and have fixed this.
Thank you

**Comment by wolfshow** [comment]
@shreyaschim We recommend using GPU with at least 8GB memory and make sure using "--max_seq_length 512"

**Comment by shreyaschim** [comment]
> @shreyaschim We recommend using GPU with at least 8GB memory and make sure using "--max_seq_length 512"
thanks for reply.
