### ISSUE TITLE
sroie index out of range

### ISSUE THREAD

**Issue by juvebogdan** [microsoft/unilm#271]
Hello, 

I am trying to fine tune LayoutLm for SROIE receipt named entity extraction. I prepared the data to be same as funds. First lines from train.txt looks like this:

```
3-1708032	O
Wotsons	O
Watson's	B-COMPANY
Personal	I-COMPANY
Care	I-COMPANY
Stores	I-COMPANY
Sdn	I-COMPANY
Bhd	E-COMPANY
Company	O
Reg	O
No.	O
:	O
289892V	O
GST	O
Reg	O
No.	O
000947339264	O
USJ	B-ADDRESS
Summit	I-ADDRESS
,	I-ADDRESS
Subang	I-ADDRESS
SS	I-ADDRESS
}	E-ADDRESS
22241	O
```

I created train_box.txt and train_image.txt using same preprocess script from funds that calls that seq() function.
I also normalized boundig boxes. First lines from train_box.txt look like this:

```
3-1708032	336 18 731 44
Wotsons	242 74 752 104
Watson's	123 118 271 134
Personal	295 118 440 134
Care	468 118 541 134
Stores	564 118 676 134
Sdn	697 118 751 134
Bhd	764 118 827 134
Company	256 133 386 151
Reg	409 133 463 151
No.	487 133 536 151
:	567 133 580 151
289892V	588 133 717 151
GST	256 149 310 165
Reg	331 149 390 165
No.	413 149 465 165
000947339264	491 149 717 165
USJ	256 162 318 181
Summit	333 163 440 181
,	453 163 465 181
Subang	510 163 616 182
SS	658 165 694 183
}	708 165 718 183
22241	102 195 188 212
```

After that I used your run_seq_labelling.py but I get the following error:

```
Iteration:   4%|█████▉                                                                                                                                                             | 21/577 [00:53<23:45,  2.56s/it]
Epoch:   0%|                                                                                                                                                                                | 0/100 [00:53<?, ?it/s]
Traceback (most recent call last):
  File "run_seq_labeling.py", line 812, in <module>
    main()
  File "run_seq_labeling.py", line 705, in main
    args, train_dataset, model, tokenizer, labels, pad_token_label_id
  File "run_seq_labeling.py", line 220, in train
    outputs = model(**inputs)
  File "/home/ml3/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ml3/.local/lib/python3.6/site-packages/layoutlm/modeling/layoutlm.py", line 221, in forward
    head_mask=head_mask,
  File "/home/ml3/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ml3/.local/lib/python3.6/site-packages/layoutlm/modeling/layoutlm.py", line 171, in forward
    input_ids, bbox, position_ids=position_ids, token_type_ids=token_type_ids
  File "/home/ml3/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ml3/.local/lib/python3.6/site-packages/layoutlm/modeling/layoutlm.py", line 82, in forward
    bbox[:, :, 2] - bbox[:, :, 0]
  File "/home/ml3/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ml3/.local/lib/python3.6/site-packages/torch/nn/modules/sparse.py", line 126, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "/home/ml3/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 1814, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
IndexError: index out of range in self
```

I checked dimensions of input_ids and its always the same as for funsd

Can you help me with this? Am I missing something in this setup?

**Comment by juvebogdan** [comment]
I figured it out. Turns out that my OCR detects some handwritten text that happens to be vertical and in that case widht comes up as negative in Embeddings.

**Comment by rgvananth** [comment]
> I figured it out. Turns out that my OCR detects some handwritten text that happens to be vertical and in that case widht comes up as negative in Embeddings.

How did you solve this?

**Comment by juvebogdan** [comment]
Some of the receipts contain some handwritten text that comes in as vertical. It looks like that layoutlm needs horizontal text. So for every bounding box your OCR outputs you need to make sure its horiznotal. x1,y1,x2,y2 always needs to be x2>x1 and y2>y1
