### ISSUE TITLE
Problem with lxml and layoutlm  

### ISSUE THREAD

**Issue by AdnanHoque** [microsoft/unilm#291]
Using the sample data folder provided for **Layoutlm Document Image Classification Task** I get the following error: 
```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/path/anaconda3/envs/layoutlm/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/path/anaconda3/envs/layoutlm/lib/python3.6/site-packages/layoutlm/data/rvl_cdip.py", line 61, in worker
    text, bbox = self.read_hocr_file(self.data_dir, file)
  File "//anaconda3/envs/layoutlm/lib/python3.6/site-packages/layoutlm/data/rvl_cdip.py", line 89, in read_hocr_file
    doc = html.parse(hocr_file)
  File "/path/anaconda3/envs/layoutlm/lib/python3.6/site-packages/lxml/html/__init__.py", line 939, in parse
    return etree.parse(filename_or_url, parser, base_url=base_url, **kw)
  File "src/lxml/etree.pyx", line 3521, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1839, in lxml.etree._parseDocument
  File "src/lxml/parser.pxi", line 1865, in lxml.etree._parseDocumentFromURL
  File "src/lxml/parser.pxi", line 1769, in lxml.etree._parseDocFromFile
  File "src/lxml/parser.pxi", line 1163, in lxml.etree._BaseParser._parseDocFromFile
  File "src/lxml/parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 711, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 638, in lxml.etree._raiseParseError
OSError: Error reading file '/path/to/data/images/imagesi/i/z/u/izu65e00/2045620940.xml': failed to load external entity "/path/to/data/images/imagesi/i/z/u/izu65e00/2045620940.xml"
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run_classification.py", line 724, in <module>
    main()
  File "run_classification.py", line 625, in main
    train_dataset = load_and_cache_examples(args, tokenizer, mode="train")
  File "/path/anaconda3/envs/layoutlm/lib/python3.6/site-packages/layoutlm/data/rvl_cdip.py", line 277, in load_and_cache_examples
    examples = processor.get_examples(args.data_dir, mode)
  File "path/anaconda3/envs/layoutlm/lib/python3.6/site-packages/layoutlm/data/rvl_cdip.py", line 70, in get_examples
    for example in p.imap(self.worker, lines):
  File "/path/anaconda3/envs/layoutlm/lib/python3.6/multiprocessing/pool.py", line 735, in next
    raise value
OSError: Error reading file '/path/to/datai/i/z/u/izu65e00/2045620940.xml': failed to load external entity "/path/to/data/imagesi/i/z/u/izu65e00/2045620940.xml"
```
Any idea what could be causing this?

**Comment by lucky-verma** [comment]
how did you resolve this issue? I'm stuck with the same error.
