### ISSUE TITLE
python decode_seq2seq.py .......--beam_size 5.......  An error occurred

### ISSUE THREAD

**Issue by guijuzhejiang** [microsoft/unilm#297]
- Platform:
- Python version:3.8
- PyTorch version (GPU?):1.7.1
- 
- **Describe the bug**
I am using MiniLM Model of Japanese languages I trained myself:

When I exec python decode_seq2seq.py .......--beam_size 5......., the following error occurred

Traceback (most recent call last):
  File "/home/zzg/.conda/envs/ML_py38/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3417, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-0eeacfaf3bdb>", line 3, in <module>
    runfile('/home/zzg/workspace/pycharm/unilm/s2s-ft/decode_seq2seq.py', wdir='/home/zzg/workspace/pycharm/unilm/s2s-ft')
  File "/opt/pycharm-2020.1.3/plugins/python/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/opt/pycharm-2020.1.3/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/zzg/workspace/pycharm/unilm/s2s-ft/decode_seq2seq.py", line 268, in <module>
    main()
  File "/home/zzg/workspace/pycharm/unilm/s2s-ft/decode_seq2seq.py", line 222, in main
    traces = model(input_ids, token_type_ids,
  File "/home/zzg/.conda/envs/ML_py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/zzg/workspace/pycharm/unilm/s2s-ft/s2s_ft/modeling_decoding.py", line 1385, in forward
    return self.beam_search(input_ids, token_type_ids, position_ids, attention_mask, task_idx=task_idx, mask_qkv=mask_qkv)
  File "/home/zzg/workspace/pycharm/unilm/s2s-ft/s2s_ft/modeling_decoding.py", line 1586, in beam_search
    prev_embedding = select_beam_items(
  File "/home/zzg/workspace/pycharm/unilm/s2s-ft/s2s_ft/modeling_decoding.py", line 1558, in select_beam_items
    y = torch.gather(x, 1, ids)
RuntimeError: gather_out_cuda(): Expected dtype int64 for index

I think the problem is the 1529 line of unilm/s2s-ft/s2s_ft/modeling_decoding.py：
back_ptrs = torch.div(k_ids, K)
K is the beam width. So back_ptrs becomes a float instead of int64.
If beam search cannot be used in Japanese？

**Comment by addf400** [comment]
@guijuzhejiang 
I read this "If input is of type FloatTensor or DoubleTensor, other should be a real number, otherwise it should be an integer" from https://pytorch.org/docs/1.2.0/torch.html?highlight=div#torch.div

Seems "K is the beam width. So back_ptrs becomes a float instead of int64." will not happen.
Can you provide more details?

**Comment by piskunow** [comment]
I encountered the same issue. @donglixp, why is the issue closed without explanation nor solution?

The problem is indeed with `torch.div`. As of version `1.6`, the torch developers decided to make better sense of type upcasting,
and as of version `1.8` they added a parameter `rounding_mode` to `torch.div` let you decide the type of division.

With earlier versions of `torch` (such as `1.6` or `1.7`), `torch.floor_divide` should be used for integer division;
and `torch.div(*args, rounding_mode='floor')` may be used since version `1.8`.

The line that needs to be updated is 

https://github.com/microsoft/unilm/blob/master/s2s-ft/s2s_ft/modeling_decoding.py#L1529

using `torch.floor_divide`.

**Comment by donglixp** [comment]
@piskunow Thanks! I've merged the PR.
