### ISSUE TITLE
Transformer learning with different vocab_size

### ISSUE THREAD

**Issue by guijuzhejiang** [microsoft/unilm#299]
I am using UniLM1.2 to transformer learning the SequenceToSequence architecture.
I want to do transfer learning on jp vocab which vocab size is different from english vocab size.
I think when loading the model parameters, the parameters related to the final classification of vocab should be deleted.
How can I transformer learning with different vocab size?

**Comment by guijuzhejiang** [comment]
Adding the modified vocab code:
model.resize_token_embeddings(new_num_tokens)
It still reports an error:
Traceback (most recent call last):
  File "/home/zzg/workspace/pycharm/unilm/s2s-ft/run_seq2seq.py", line 415, in <module>
    main()
  File "/home/zzg/workspace/pycharm/unilm/s2s-ft/run_seq2seq.py", line 398, in main
    model, tokenizer = get_model_and_tokenizer(args)
  File "/home/zzg/workspace/pycharm/unilm/s2s-ft/run_seq2seq.py", line 386, in get_model_and_tokenizer
    model.resize_token_embeddings(new_num_tokens=25960)
  File "/home/zzg/.conda/envs/ML_py38/lib/python3.8/site-packages/transformers/modeling_utils.py", line 371, in resize_token_embeddings
    model_embeds = base_model._resize_token_embeddings(new_num_tokens)
  File "/home/zzg/.conda/envs/ML_py38/lib/python3.8/site-packages/transformers/modeling_utils.py", line 385, in _resize_token_embeddings
    old_embeddings = self.get_input_embeddings()
  File "/home/zzg/.conda/envs/ML_py38/lib/python3.8/site-packages/transformers/modeling_utils.py", line 303, in get_input_embeddings
    raise NotImplementedError
NotImplementedError
Because the transformers version=2.10.0, So it had not been implemented.
And the project of unilm does not support transformers >2.10.0.
what should I do?

**Comment by guijuzhejiang** [comment]
Adding the modified vocab code:
model.resize_token_embeddings(new_num_tokens)
It still reports an error:
Traceback (most recent call last):
  File "/home/zzg/workspace/pycharm/unilm/s2s-ft/run_seq2seq.py", line 415, in <module>
    main()
  File "/home/zzg/workspace/pycharm/unilm/s2s-ft/run_seq2seq.py", line 398, in main
    model, tokenizer = get_model_and_tokenizer(args)
  File "/home/zzg/workspace/pycharm/unilm/s2s-ft/run_seq2seq.py", line 386, in get_model_and_tokenizer
    model.resize_token_embeddings(new_num_tokens=25960)
  File "/home/zzg/.conda/envs/ML_py38/lib/python3.8/site-packages/transformers/modeling_utils.py", line 371, in resize_token_embeddings
    model_embeds = base_model._resize_token_embeddings(new_num_tokens)
  File "/home/zzg/.conda/envs/ML_py38/lib/python3.8/site-packages/transformers/modeling_utils.py", line 385, in _resize_token_embeddings
    old_embeddings = self.get_input_embeddings()
  File "/home/zzg/.conda/envs/ML_py38/lib/python3.8/site-packages/transformers/modeling_utils.py", line 303, in get_input_embeddings
    raise NotImplementedError
NotImplementedError
Because the transformers version=2.10.0, So it had not been implemented.
And the project of unilm does not support transformers >2.10.0.
what should I do?

**Comment by addf400** [comment]
@guijuzhejiang Is to replace the token embedding parameter of the model? Or reinitialize it?

**Comment by guijuzhejiang** [comment]
It is replace the token embedding parameter,Because the vocab size has changed.

**Comment by addf400** [comment]
> It is replace the token embedding parameter,Because the vocab size has changed.

A simple solution: create another model with vocab size you need, and replace the token embedding just like: 
```python
model.encoder.embedding.token_embedding = new_model.encoder.embedding.token_embedding
```

**Comment by guijuzhejiang** [comment]
Thank you very much for your answer,it worked.
