### ISSUE TITLE
    if kwargs["state_dict"] is None: KeyError: 'state_dict'

### ISSUE THREAD

**Issue by JeremySun1224** [microsoft/unilm#306]
**Describe**
Model I am using (unilm1.2-base-uncased):
```
Traceback (most recent call last):
  File "run_seq2seq.py", line 410, in <module>
    main()
  File "run_seq2seq.py", line 393, in main
    model, tokenizer = get_model_and_tokenizer(args)
  File "run_seq2seq.py", line 192, in get_model_and_tokenizer
    cache_dir=args.cache_dir if args.cache_dir else None)
  File "/home/aistudio/gen_coqa/s2s-ft/s2s_ft/modeling.py", line 90, in from_pretrained
    if kwargs["state_dict"] is None:
KeyError: 'state_dict'
```
The buggy code is here, third line from the bottom:
```
    def from_pretrained(cls, pretrained_model_name_or_path, reuse_position_embedding=None, *model_args, **kwargs):
        model_type = kwargs.pop('model_type', None)
        if model_type is not None and "state_dict" not in kwargs:
            if model_type in cls.supported_convert_pretrained_model_archive_map:
                pretrained_model_archive_map = cls.supported_convert_pretrained_model_archive_map[model_type]
                if pretrained_model_name_or_path in pretrained_model_archive_map:
                    state_dict = get_checkpoint_from_transformer_cache(
                        archive_file=pretrained_model_archive_map[pretrained_model_name_or_path],
                        pretrained_model_name_or_path=pretrained_model_name_or_path,
                        pretrained_model_archive_map=pretrained_model_archive_map,
                        cache_dir=kwargs.get("cache_dir", None), force_download=kwargs.get("force_download", None),
                        proxies=kwargs.get("proxies", None), resume_download=kwargs.get("resume_download", None),
                    )
                    state_dict = state_dict_convert[model_type](state_dict)
                    kwargs["state_dict"] = state_dict
                elif os.path.isfile(pretrained_model_name_or_path):
                    kwargs["state_dict"] = torch.load(pretrained_model_name_or_path, map_location='cpu')

        if kwargs["state_dict"] is None:
            logger.info("s2s-ft does't support the model !")
            raise NotImplementedError()
```

- Platform: Linux
- Python version: python==3.7.4
- PyTorch version (GPU?): torch1.1.0, 
- GPU: one  32G Tesla V100 GPU

Here is my shell script:
```
export OUTPUT_DIR="Experiments/QAQAFQ"
# export CACHE_DIR=transformer_package_cache
CUDA_VISIBLE_DEVICES=0
python run_seq2seq.py --train_file "CoQA/QAQAFQ/train.json"  --output_dir ${OUTPUT_DIR} \
  --model_type unilm --model_name_or_path "/home/aistudio/pretrained_model/unilm1.2-base-uncased/" \
  --do_lower_case --max_source_seq_length 470 --max_target_seq_length 42 --per_gpu_train_batch_size 6 \
  --gradient_accumulation_steps 4 --learning_rate 2e-5  --num_warmup_steps 2236 --num_training_epochs 10 \
  --save_steps 77777  \
```
A peer and I encountered a similar bug, but I followed that method and it didn't work for me.
The link is here #99

Please help me, thank you very much!

**Comment by addf400** [comment]
@JeremySun1224 Please set --model_name_or_path to the checkpoint file, not folder.
Like `--model_name_or_path /home/aistudio/pretrained_model/unilm1.2-base-uncased/pytorch_model.bin`
And set `--config_name` to the model's json config file.

**Comment by JeremySun1224** [comment]
@addf400 Thank you very much for the guidance, it worked for me.
