### ISSUE TITLE
CUDA out of memory with T4 GPU

### ISSUE THREAD

**Issue by tengerye** [microsoft/unilm#420]
**Describe the bug**
Model I am using is LayoutLM.

The problem arises when using:
My own modified scripts: `python3 -m torch.distributed.launch --nproc_per_node=4 examples/run_xfun_ser.py --model_name_or_path microsoft/layoutxlm-base --output_dir /tmp/test-ner --do_train --do_eval --lang zh --max_steps 1000 --warmup_ratio 0.1 --fp16 --per_device_train_batch_size 2 --per_device_eval_batch_size 1 --max_seq_length 512`

**Expected behavior**
The traceback is:
```
Traceback (most recent call last):
  File "examples/run_xfun_ser.py", line 297, in <module>
    main()
  File "examples/run_xfun_ser.py", line 46, in main
    model_args, data_args, training_args = parser.parse_args_into_dataclasses()  # Use the arguments as parameters for the ModelArguments classes.
  File "/data00/home/someone/miniconda3/envs/layoutlmft/lib/python3.7/site-packages/transformers/hf_argparser.py", line 187, in parse_args_into_dataclasses
    obj = dtype(**inputs)
  File "<string>", line 67, in __init__
  File "/data00/home/someone/miniconda3/envs/layoutlmft/lib/python3.7/site-packages/transformers/training_args.py", line 570, in __post_init__
    if is_torch_available() and self.device.type != "cuda" and (self.fp16 or self.fp16_full_eval):
  File "/data00/home/someone/miniconda3/envs/layoutlmft/lib/python3.7/site-packages/transformers/file_utils.py", line 1470, in wrapper
    return func(*args, **kwargs)
  File "/data00/home/someone/miniconda3/envs/layoutlmft/lib/python3.7/site-packages/transformers/training_args.py", line 717, in device
    return self._setup_devices
  File "/data00/home/someone/miniconda3/envs/layoutlmft/lib/python3.7/site-packages/transformers/file_utils.py", line 1460, in __get__
    cached = self.fget(obj)
  File "/data00/home/someone/miniconda3/envs/layoutlmft/lib/python3.7/site-packages/transformers/file_utils.py", line 1470, in wrapper
    return func(*args, **kwargs)
  File "/data00/home/someone/miniconda3/envs/layoutlmft/lib/python3.7/site-packages/transformers/training_args.py", line 702, in _setup_devices
    torch.distributed.init_process_group(backend="nccl")
  File "/data00/home/someone/miniconda3/envs/layoutlmft/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 455, in init_process_group
    barrier()
  File "/data00/home/someone/miniconda3/envs/layoutlmft/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1960, in barrier
    work = _default_pg.barrier()
RuntimeError: CUDA error: out of memory
Traceback (most recent call last):
  File "examples/run_xfun_ser.py", line 297, in <module>
    main()
  File "examples/run_xfun_ser.py", line 46, in main
    model_args, data_args, training_args = parser.parse_args_into_dataclasses()  # Use the arguments as parameters for the ModelArguments classes.
  File "/data00/home/someone/miniconda3/envs/layoutlmft/lib/python3.7/site-packages/transformers/hf_argparser.py", line 187, in parse_args_into_dataclasses
    obj = dtype(**inputs)
  File "<string>", line 67, in __init__
  File "/data00/home/someone/miniconda3/envs/layoutlmft/lib/python3.7/site-packages/transformers/training_args.py", line 570, in __post_init__
    if is_torch_available() and self.device.type != "cuda" and (self.fp16 or self.fp16_full_eval):
  File "/data00/home/someone/miniconda3/envs/layoutlmft/lib/python3.7/site-packages/transformers/file_utils.py", line 1470, in wrapper
    return func(*args, **kwargs)
  File "/data00/home/someone/miniconda3/envs/layoutlmft/lib/python3.7/site-packages/transformers/training_args.py", line 717, in device
    return self._setup_devices
  File "/data00/home/someone/miniconda3/envs/layoutlmft/lib/python3.7/site-packages/transformers/file_utils.py", line 1460, in __get__
    cached = self.fget(obj)
  File "/data00/home/someone/miniconda3/envs/layoutlmft/lib/python3.7/site-packages/transformers/file_utils.py", line 1470, in wrapper
    return func(*args, **kwargs)
  File "/data00/home/someone/miniconda3/envs/layoutlmft/lib/python3.7/site-packages/transformers/training_args.py", line 702, in _setup_devices
    torch.distributed.init_process_group(backend="nccl")
  File "/data00/home/someone/miniconda3/envs/layoutlmft/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 455, in init_process_group
    barrier()
  File "/data00/home/someone/miniconda3/envs/layoutlmft/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1960, in barrier
    work = _default_pg.barrier()
RuntimeError: CUDA error: out of memory
```

**Environments**
- Platform: Debian
- Python version: Python 3.7.9
- PyTorch version: 1.7.1+cu101
- GPU: Tesla T4 (16G)

**Comment by tengerye** [comment]
I am using T4 GPU by the way. @ranpox

**Comment by tengerye** [comment]
If we run without torch.distributed.launch, such as `python3 -u examples/run_xfun_ser.py --model_name_or_path microsoft/layoutxlm-base --output_dir /tmp/test-ner-35 --do_train --do_eval --lang zh --max_steps 1000 --warmup_ratio 0.1 --fp16 --per_device_train_batch_size 2 --per_device_eval_batch_size 2`, we will have the following error:
```  File "/data00/home/someone/projects/unilm/layoutlmft/examples/run_xfun_ser.py", line 296, in <module>
    main()
  File "/data00/home/someone/projects/unilm/layoutlmft/examples/run_xfun_ser.py", line 241, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/data00/home/someone/anaconda3/envs/layoutlmft/lib/python3.7/site-packages/transformers/trainer.py", line 1120, in train
    tr_loss += self.training_step(model, inputs)
  File "/data00/home/someone/anaconda3/envs/layoutlmft/lib/python3.7/site-packages/transformers/trainer.py", line 1522, in training_step
    loss = self.compute_loss(model, inputs)
  File "/data00/home/someone/anaconda3/envs/layoutlmft/lib/python3.7/site-packages/transformers/trainer.py", line 1556, in compute_loss
    outputs = model(**inputs)
  File "/data00/home/someone/anaconda3/envs/layoutlmft/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data00/home/someone/anaconda3/envs/layoutlmft/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 161, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/data00/home/someone/anaconda3/envs/layoutlmft/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 171, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/data00/home/someone/anaconda3/envs/layoutlmft/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/data00/home/someone/anaconda3/envs/layoutlmft/lib/python3.7/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/data00/home/someone/anaconda3/envs/layoutlmft/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/data00/home/someone/anaconda3/envs/layoutlmft/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data00/home/someone/projects/unilm/layoutlmft/layoutlmft/models/layoutlmv2/modeling_layoutlmv2.py", line 864, in forward
    return_dict=return_dict,
  File "/data00/home/someone/anaconda3/envs/layoutlmft/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data00/home/someone/projects/unilm/layoutlmft/layoutlmft/models/layoutlmv2/modeling_layoutlmv2.py", line 779, in forward
    position_ids=visual_position_ids,
  File "/data00/home/someone/projects/unilm/layoutlmft/layoutlmft/models/layoutlmv2/modeling_layoutlmv2.py", line 668, in _calc_img_embeddings
    embeddings = visual_embeddings + position_embeddings + spatial_position_embeddings
RuntimeError: The size of tensor a (4) must match the size of tensor b (2) at non-singleton dimension 0
```

**Comment by wgx998877** [comment]
Hi tengerye,

For the first OOM issue, would you mind to try to reduce the batch_size to 1 and test it again? And can you monitor the GPU memory usage at that time?

For the second issue, seems there are some implementation issues from your code, so you can log the size of visual_embeddings, position_embeddings, spatial_position_embeddings. And I would assume the batch size of these three tensor are different, so we can do the following debugging process.

**Comment by tengerye** [comment]
@wgx998877 Thank you for your kind reply.
For the first issue, batch_size=1 works, but it is not essentially a OOM issue. The reason is the T4 GPU has 16G memory, which is surely capable for the batch_size=2.

After all, I have located the problem. It will be triggered if you run without DDP but with multiple GPUs. In more details, the error rises because the Detectron2 does not support DP while huggingface does.

In my humble option, I would suggest decouple the training from the huggingface framework.
