### ISSUE TITLE
TROCR inference

### ISSUE THREAD

**Issue by darraghdog** [microsoft/unilm#458]
Hi, I am trying to run inference on the `pic_inference.py` and it is failing at the loading of the weights. See details below. Thanks!
Model I am using - UniLM TrOCR, with weights file [TrOCR-Base-IAM](https://layoutlm.blob.core.windows.net/trocr/model_zoo/fairseq/trocr-base-handwritten.pt) 

The problem arises when using:
*  `pic_inference.py`

**To Reproduce**
Run,
```
import task
import deit
import pandas as pd
import deit_models
import torch
import fairseq
from fairseq import utils
from fairseq_cli import generate
from PIL import Image
import torchvision.transforms as transforms
model_path = '../../../trocr-base-handwritten.pt'
beam = 5
model, cfg, task = fairseq.checkpoint_utils.load_model_ensemble_and_task(
        [model_path],
        arg_overrides={"beam": beam, "task": "text_recognition", "data": "", "fp16": False})
```
Gives error message
```
| [label] load dictionary: 50265 types
Traceback (most recent call last):

  File "<ipython-input-1-d64264010de2>", line 18, in <module>
    arg_overrides={"beam": beam, "task": "text_recognition", "data": "", "fp16": False})

  File "/Users/dhanley/Documents/xfrmr-proto/pkgs/fairseq/fairseq/checkpoint_utils.py", line 457, in load_model_ensemble_and_task
    model = task.build_model(cfg.model)

  File "/Users/dhanley/Documents/xfrmr-proto/pkgs/fairseq/fairseq/tasks/fairseq_task.py", line 651, in build_model
    model = models.build_model(args, self)

  File "/Users/dhanley/Documents/xfrmr-proto/pkgs/fairseq/fairseq/models/__init__.py", line 107, in build_model
    return model.build_model(cfg, task)

  File "/Users/dhanley/Documents/xfrmr-proto/pkgs/unilm/trocr/deit_models.py", line 400, in build_model
    dictionary = task.source_dictionary

  File "/Users/dhanley/Documents/xfrmr-proto/pkgs/unilm/trocr/deit_models.py", line 642, in __init__
    self.deit = create_model(args.deit_arch, pretrained=True, ape=args.ape, mask_ratio=args.mask_ratio)

  File "/Users/dhanley/anaconda3/lib/python3.7/site-packages/timm/models/factory.py", line 81, in create_model
    model = create_fn(pretrained=pretrained, **kwargs)

  File "/Users/dhanley/Documents/xfrmr-proto/pkgs/unilm/trocr/deit.py", line 332, in beit_base_patch16_384
    norm_layer=partial(nn.LayerNorm, eps=1e-6), **kwargs)

  File "/Users/dhanley/Documents/xfrmr-proto/pkgs/unilm/trocr/deit.py", line 128, in __init__
    super().__init__(img_size=img_size, patch_size=patch_size, in_chans=in_chans, num_classes=num_classes, embed_dim=embed_dim, depth=depth, num_heads=num_heads, mlp_ratio=mlp_ratio, qkv_bias=qkv_bias, qk_scale=qk_scale, representation_size=representation_size, drop_rate=drop_rate, attn_drop_rate=attn_drop_rate, drop_path_rate=drop_path_rate, hybrid_backbone=hybrid_backbone, norm_layer=norm_layer)

TypeError: __init__() got an unexpected keyword argument 'hybrid_backbone'
```

System
```
- Platform: MacOS (Python 3.7.6) and linux (Python 3.8.10)
- PyTorch version (GPU): torch==1.9.1 on linux with a100 gpu card. 
```

**Comment by Dod-o** [comment]
@darraghdog Does it report the same or other errors when you run the training or evaluation?

**Comment by darraghdog** [comment]
Thanks @Dod-o , I see the requiremnts have a different version of fairseq and torch. I will get these set up and retry. I'm sure this is the issue - will close for now.
