### ISSUE TITLE
Unclear input data structure of layoutreader

### ISSUE THREAD

**Issue by 7fantasysz** [microsoft/unilm#464]
**Describe**
Model I am using (layoutreader): How should I prepare my input data to use script decode_seq2seq.py and the pretrained model? It's not clearly stated anywhere and please help.

**Comment by zlwang-cs** [comment]
@ManuelFay Thank you for the great job! As for your question, we run LayoutReader on ReadingBank dataset and we filter out the pages with more than 511 tokens. For other datasets, I agree the sliding window is a feasible solution.

**Comment by myh12138** [comment]
> @SimeonZhang Hi, it is easy to run LayoutReader in `text only` settings by using the corresponding `model_name` and `model_name_or_path` in args. You can also run the `layout only` settings with the `layoutlm_only_layout` flag in args. As for different shuffle rates, you can try the `sentence_shuffle_rate` in args.

hi，when I change input_folder to my data and make layoutlm_only_layout ,the progress still shows the original data?
Can you give me some suggestions? Thanks

**Comment by HoomanKhosravi** [comment]
@HYPJUDY  @ManuelFay  Thank you for sharing your code. I was wondering what's your approach with sorting in top-down / left-right? do you look at bottom and left of bboxes? do you know if reading bank data is sorted in this manner?

**Comment by ManuelFay** [comment]
From the LayoutReader paper it is mentionned it is best to do so. It's then just a matter of sorting the list with a double key in Python, take any point from the boxes as long as it's consistent. 
Note that some libraries (pdfplumber with textflow, pytesseract) include a text orderer usually better than the top-down-left-right heuristic that might be easier to use !
Cheers !

**Comment by HoomanKhosravi** [comment]
> From the LayoutReader paper it is mentionned it is best to do so. It's then just a matter of sorting the list with a double key in Python, take any point from the boxes as long as it's consistent. Note that some libraries (pdfplumber with textflow, pytesseract) include a text orderer usually better than the top-down-left-right heuristic that might be easier to use ! Cheers !

Thanks!

**Comment by animebing** [comment]
> From the LayoutReader paper it is mentionned it is best to do so. It's then just a matter of sorting the list with a double key in Python, take any point from the boxes as long as it's consistent. Note that some libraries (pdfplumber with textflow, pytesseract) include a text orderer usually better than the top-down-left-right heuristic that might be easier to use ! Cheers !

I use `bboxes = sorted(bboxes, lambda x:[x[0], x[1]])` to get left-right-top-down order and adjust texts accordingly, but I find the result is much worse than the order from Tesseract, which confuses me a lot, can you give me some suggestions about it, thanks

**Comment by tengerye** [comment]
Hi, maybe there is something wrong in function [`load_and_cache_line_order_examples`](https://github.com/microsoft/unilm/blob/e4929f812398207b7fefb4dda6e9debcb8ce34b9/layoutreader/s2s_ft/utils.py#L339) as well?

It tries to load a single file only. However, it is expected to load several files from a folder, as in function `load_and_cache_layoutlm_examples`.

**Comment by zlwang-cs** [comment]
Actually, the [load_and_cache_line_order_examples](https://github.com/microsoft/unilm/blob/e4929f812398207b7fefb4dda6e9debcb8ce34b9/layoutreader/s2s_ft/utils.py#L339) is deprecated. You can reproduce a similar function if you need to conduct such experiments.

**Comment by vprecup** [comment]
I have tried loading the model (for evaluation / decode) as instructed above, but I was not able to bypass the following input data-related error. I limited the inputs to just the first data chunk (m1) from the test set.

```
10/31/2022 10:51:48 - INFO - s2s_ft.modeling_decoding -   Weights of LayoutlmForSeq2SeqDecoder not initialized from pretrained model: ['bert.pooler.dense.weight', 'bert.pooler.dense.bias', 'cls.seq_relationship.weight', 'cls.seq_relationship.bias']
10/31/2022 10:51:48 - INFO - s2s_ft.modeling_decoding -   Weights from pretrained model not used in LayoutlmForSeq2SeqDecoder: ['crit_mask_lm_smoothed.one_hot']
10/31/2022 10:51:49 - INFO - s2s_ft.utils -   Creating features from dataset at data/exp-ocr-formatting/layout_reader_data/test
10/31/2022 10:51:49 - INFO - s2s_ft.utils -   Start loading data/exp-ocr-formatting/layout_reader_data/test/dataset-test-s2s-text-m1.json
100%|███████████████████████████████████████| 7722/7722 [02:44<00:00, 47.04it/s]
  0%|                                                  | 0/1931 [00:00<?, ?it/s]10/31/2022 10:54:41 - INFO - s2s_ft.s2s_loader -   Input src = [CLS] ( a ) ( b ) ( c ) ( d ) ( e ) ( f ) ( g ) ( h ) 08 ##00 - 09 ##10 history of ghana armed forces l ah g ##h ##q ( ed ##n ) 09 ##15 - 104 ##0 review sv ##c writing 1 , 2 & 3 d sr sd ##s wed 104 ##5 - 111 ##5 coffee break - mess 12 sep 18 112 ##0 - 124 ##0 review sv ##c writing 1 , 2 & 3 d sr sd ##s 124 ##5 - 133 ##0 library orientation - library librarian 133 ##5 - 145 ##5 lunch 1500 - 1800 research methods md ##ip ah dr n ku ##rant ##in md ##ip 501 501 05 ##30 - 06 ##30 physical training pt pt 48 eng ##r pt ##is 08 ##30 - 09 ##55 review sv ##c writing 4 - d reg ##t sd ##s th ##u 1000 - 104 ##0 communication : definition , types and barriers to - l sr u of g 13 sep 18 communication ah coffee break 104 ##5 - 111 ##5 communication : definition , types and barriers to 112 ##0 - 1200 - l u of g communication ( con ##t ) ah speaking and listening skills in communication 120 ##5 - 124 ##5 l u of g ah effective speaking : strategies in communication 125 ##0 - 134 ##0 l u of g ah lunch 134 ##5 - 143 ##0 - - research methods 1500 - 1800 md ##ip mess dr n ku ##rant ##in md ##ip ah 501 501 08 ##00 - 08 ##35 p ah dc ##a cultural awareness fr ##i 08 ##30 - 104 ##0 d sr ds os ##w introduction and review os ##w 1 & 2 14 sep 18 104 ##5 - 111 ##5 coffee break issue of cs ##t 1 112 ##0 - 134 ##0 effective writing ( techniques for clarity in - l ah u of g sentence , writing balance prose , techniques for essay writing ) lunch 1400 - 145 ##5 md ##ip md ##ip research methods 1500 - 1800 ah dr n ku ##rant ##in 501 501 sat 15 sep 09 ##00 - 1500 cultural orientation acc ##ra acc ##ra dc ##a – for [SEP] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD]
  0%|                                                  | 0/1931 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "data/exp-ocr-formatting/layout_reader/unilm/layoutreader/decode_seq2seq.py", line 345, in <module>
    main()
  File "data/exp-ocr-formatting/layout_reader/unilm/layoutreader/decode_seq2seq.py", line 271, in main
    instances.append(proc(instance))
  File "/Users/vprecup/Code/ml-sds-notebooks/notebooks/data/exp-ocr-formatting/layout_reader/unilm/layoutreader/s2s_ft/s2s_loader.py", line 162, in __call__
    input_mask[second_st:second_end, second_st:second_end].copy_(
RuntimeError: The size of tensor a (0) must match the size of tensor b (511) at non-singleton dimension 1
```

**Comment by alejandrojcastaneira** [comment]
Hi @ManuelFay thanks for sharing the code, I tried and works really well! , one question, do you have any suggestions on how to optimize the inference time, I notice it took like 7 seconds for a single doc.

**Comment by ManuelFay** [comment]
> Hi @ManuelFay thanks for sharing the code, I tried and works really well!, one question, do you have any suggestions on how to optimize the inference time, I notice it takes like 7 seconds for a single doc.

It is really long... The authors recommend a few things in the repo (cuda libs to go faster and do ops in a quantized way). Apart from that, simplest is probably to use heuristics to split the page into "safe" subpages and then reconstruct them one at a time since speed is square proportional to sequence length in transformers. It does kind of lose most of it's purpose though... 
Maybe the authors are working on a more efficient model or have tips

**Comment by logan-markewich** [comment]
@ManuelFay this code should definitely be added to the repo! I almost gave up trying to use this model lol. Thanks for the help.

**Comment by logan-markewich** [comment]
Thank you for the code @ManuelFay ! Unfortunately, the results are not great with tesseract as input. At least I could test it though :)

**Comment by Jesteinbe** [comment]
This may be a naive question but are the layout-only results reported in the paper obtained by running inference with the model trained on layout+text but without any token embeddings or is it a different model trained on layout-only features? I thought it was the latter but the above posts make me think it might be the former.

Also, based on what I'm seeing should we only be using the `--layoutlm_only_layout` but not `--layout_only_dataset`? If the latter is used then it forces the use of the deprecated [load_and_cache_line_order_examples](https://github.com/microsoft/unilm/blob/e4929f812398207b7fefb4dda6e9debcb8ce34b9/layoutreader/s2s_ft/utils.py#L339). However, if we don't specify `--layout_only_dataset` then it loads all the text-based data. Is this the right thing to do?

**Comment by zlwang-cs** [comment]
Hi @Jesteinbe, sorry for the confusion. Let me specify the meaning of each argument. 

In our paper, we have two sets of experiments: 1) the token-level reading order (Table 2, 3, 4); 2) 2) the line-level reading order (Table 5, 6). 

In the first setting (token level), we have two changes to the standard setting: the `shuffle rate` and `w/ or w/o layout`. I assume the shuffle rate is easy to understand from the code. As for the "w/ or w/o layout", it is realized by `--layoutlm_only_layout` (standing for: the layoutlm model is used but only layout features are considered). This argument will remove the word embeddings in the model so the model can only learn from the layout information. (See Line 203 in `s2s_ft/modeling.py`). 

In the second setting (line level), the text lines are extracted by the OCR engines. Since each bounding box now corresponds to a line instead of a token, it is not straightforward to model it in the standard setting where the bounding box and word are matched to each other. So our solution is that we use placeholders as text input for each text line (see Line 370 in `s2s_ft/utils.py`). This is triggered by `--layout_only_dataset` standing for a dataset that only has layout features.

I think it is not hard to tell the difference between `load_and_cache_line_order_examples` and `load_and_cache_layoutlm_examples` from the code. And these two functions can also be used in other cases depending on the exact using scenarios.

If you have any other questions, please let us know :)

**Comment by Jesteinbe** [comment]
Thanks @zlwang-cs! I'll play around with things a bit more and let you know if I have any other questions.
