### ISSUE TITLE
Bug when training LayoutReader

### ISSUE THREAD

**Issue by WeihongM** [microsoft/unilm#473]
@HYPJUDY 
Hello, I want to train LayoutReader on my custom dataset.  I find the function [load_and_cache_line_order_examples](https://github.com/microsoft/unilm/blob/master/layoutreader/s2s_ft/utils.py#L321) in layoutreader/utils.py.
I use the below script to generate the datasetOnlyLayout.json. 
I transfer the dataset-train-s2s-text-m1.json and dataset-train-s2s-layout-m1.json into the onlyLayout.json(you provide in the readme file).
However, when I training, the error happened. Can you give me some suggestions how to deal with this information?

```
root = 'ReadingBank/ReadingBank/train'
text_file   = osp.join(root, 'dataset-train-s2s-text-m1.json')
layout_file = osp.join(root, 'dataset-train-s2s-layout-m1.json')
text_files = [text_file]
layout_files = [layout_file]

examples = []
for text_file, layout_file in zip(text_files, layout_files):
    with open(text_file, mode='r', encoding='utf-8') as text_reader, \
            open(layout_file, mode='r', encoding='utf-8') as layout_reader:
        for i, (text_line, layout_line) in enumerate(zip(text_reader, layout_reader)):
            examples.append([json.loads(text_line), json.loads(layout_line)])

save_layout = []
for i, (text, layout) in enumerate(tqdm.tqdm(examples)):
    bleu = text['bleu']
    src_layout = layout['src']
    tgt_layout = layout['tgt']
    tgt_index  = text['tgt_index']
    cur = {'src': src_layout, 'tgt':tgt_layout, 'tgt_index': tgt_index, 'bleu': bleu}
    save_layout.append(cur)

with open("dataset_onlyLayout-m1.json", "w") as f:
    for v in save_layout:
        json.dump(v, f)
        f.write('\n')
```

Error information.
```
Traceback (most recent call last):
  File "run_seq2seq.py", line 446, in <module>
    main()
  File "run_seq2seq.py", line 442, in main
    train(args, training_features, model, tokenizer)
  File "run_seq2seq.py", line 180, in train
    loss = model(**inputs)
  File "/home/weihong/anaconda3/envs/pytor1.6/lib/python3.6/site-packages/torch/nn/modules/module.py", l
ine 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/weihong/anaconda3/envs/pytor1.6/lib/python3.6/site-packages/apex-0.1-py3.6-linux-x86_64.eg
g/apex/amp/_initialize.py", line 197, in new_fwd
    **applier(kwargs, input_caster))
  File "/home/pci/disk2/weihong/experiment/exp11_unilm/layoutreader/s2s_ft/modeling.py", line 777, in fo
rward
    position_ids=position_ids, split_lengths=split_lengths, return_emb=True)
  File "/home/weihong/anaconda3/envs/pytor1.6/lib/python3.6/site-packages/torch/nn/modules/module.py", l
ine 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/pci/disk2/weihong/experiment/exp11_unilm/layoutreader/s2s_ft/modeling.py", line 612, in fo
rward
    embedding_output, attention_mask=extended_attention_mask, split_lengths=split_lengths)
  File "/home/weihong/anaconda3/envs/pytor1.6/lib/python3.6/site-packages/torch/nn/modules/module.py", l
ine 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/pci/disk2/weihong/experiment/exp11_unilm/layoutreader/s2s_ft/modeling.py", line 424, in fo
rward
    layer_outputs = layer_module(hidden_states, attention_mask, split_lengths=split_lengths)
  File "/home/weihong/anaconda3/envs/pytor1.6/lib/python3.6/site-packages/torch/nn/modules/module.py", l
ine 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/pci/disk2/weihong/experiment/exp11_unilm/layoutreader/s2s_ft/modeling.py", line 401, in fo
rward
    hidden_states, attention_mask, split_lengths=split_lengths)
  File "/home/weihong/anaconda3/envs/pytor1.6/lib/python3.6/site-packages/torch/nn/modules/module.py", l
ine 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/pci/disk2/weihong/experiment/exp11_unilm/layoutreader/s2s_ft/modeling.py", line 386, in fo
rward
    encoder_hidden_states=encoder_hidden_states, split_lengths=split_lengths)
    encoder_hidden_states=encoder_hidden_states, split_lengths=split_lengths)
  File "/home/weihong/anaconda3/envs/pytor1.6/lib/python3.6/site-packages/torch/nn/modules/module.py", l
ine 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/pci/disk2/weihong/experiment/exp11_unilm/layoutreader/s2s_ft/modeling.py", line 368, in fo
rward
    query, key, value, attention_mask[:, :, sum_length - part_length: sum_length, :sum_length]
  File "/home/pci/disk2/weihong/experiment/exp11_unilm/layoutreader/s2s_ft/modeling.py", line 333, in mu
lti_head_attention
    context_layer = context_layer.permute(0, 2, 1, 3).contiguous()
RuntimeError: CUDA error: device-side assert triggered
```

**Comment by WeihongM** [comment]
I have figured out the problem.
some additional code need to add to avoid invalid box.
```
if (not box[2] >= box[0]) or (not box[3] >= box[1]):
    continue
```
