### ISSUE TITLE
trOCR pretrained model file trocr-base-stage1.pt namespace mismatch

### ISSUE THREAD

**Issue by Lauler** [microsoft/unilm#477]
**Describe the bug**
I am using trOCR and trying to run the `pic_inference.py` script to perform inference with the `trocr-base-stage1.pt` pre-trained model checkpoint. However, the mentioned model file seems to have been given the name `DeiT_TR_larger`. This name does not exist among the registered models you have added to fairscale in `deit_models.py`. As a result user gets an error when trying to perform inference with the [trocr-base-stage1.pt](https://layoutlm.blob.core.windows.net/trocr/model_zoo/fairseq/trocr-base-stage1.pt) model file. 

Same inference code works fine with `trocr-large-stage1.pt`, but not with `base` version of model file.

The problem arises when using:
* The official example script [pic_inference.py](https://github.com/microsoft/unilm/blob/master/trocr/pic_inference.py) together with the [trocr-base-stage1.pt](https://layoutlm.blob.core.windows.net/trocr/model_zoo/fairseq/trocr-base-stage1.pt) model file.

```
python pic_inference.py
| [label] load dictionary: 50265 types
Traceback (most recent call last):
  File "pic_inference.py", line 70, in <module>
    model, cfg, task, generator, bpe, img_transform, device = init(model_path, beam)
  File "pic_inference.py", line 15, in init
    arg_overrides={"beam": beam, "task": "text_recognition", "data": "", "fp16": False})
  File "/home/faton/miniconda3/envs/trocr2/lib/python3.7/site-packages/fairseq/checkpoint_utils.py", line 387, in load_model_ensemble_and_task
    model = task.build_model(cfg.model)
  File "/home/faton/miniconda3/envs/trocr2/lib/python3.7/site-packages/fairseq/tasks/fairseq_task.py", line 633, in build_model
    model = models.build_model(args, self)
  File "/home/faton/miniconda3/envs/trocr2/lib/python3.7/site-packages/fairseq/models/__init__.py", line 93, in build_model
    + model_type
AssertionError: Could not infer model type from Namespace(_name='DeiT_TR_larger', aa='rand-m9-mstd0.5-inc1', activation_dropout=0.0, activation_fn='relu', adam_betas='(0.9, 0.999)', adam_eps=1e-08, adaptive_input=False, adaptive_softmax_cutoff=None, adaptive_softmax_dropout=0, all_gather_list_size=16384, arch='DeiT_TR_larger', attention_dropout=0.0, azureml_logging=False, batch_size=16, batch_size_valid='16', beam=5, best_checkpoint_metric='loss', bf16=False, bpe='gpt2', broadcast_buffers=False, bucket_cap_mb=25, checkpoint_activations=False, checkpoint_shard_count=1, checkpoint_suffix='', clip_norm=0.0, color_jitter=0.4, cpu=False, cpu_offload=False, criterion='cross_entropy', crop_img_output_dir=None, cross_self_attention=False, curriculum=0, data='', data_buffer_size=10, data_type='MultiHDF5', dataset_impl=None, ddp_backend='legacy_ddp', decoder_attention_heads=16, decoder_embed_dim=1024, decoder_embed_path=None, decoder_ffn_embed_dim=4096, decoder_input_dim=1024, decoder_layerdrop=0, decoder_layers=12, decoder_layers_to_keep=None, decoder_learned_pos=False, decoder_normalize_before=False, decoder_output_dim=1024, decoder_pretrained='roberta', deit_arch='beit_base_patch16_384', device_id=0, disable_validation=False, distributed_backend='nccl', distributed_init_method=None, distributed_no_spawn=False, distributed_port=-1, distributed_rank=0, distributed_world_size=8, dropout=0.1, empty_cache_freq=0, encoder_attention_heads=8, encoder_embed_dim=768, encoder_embed_path=None, encoder_ffn_embed_dim=2048, encoder_layerdrop=0, encoder_layers=6, encoder_layers_to_keep=None, encoder_learned_pos=False, encoder_normalize_before=False, eos=2, fast_stat_sync=False, find_unused_parameters=False, finetune_from_model=None, fix_batches_to_gpus=False, fixed_validation_seed=None, fp16=False, fp16_init_scale=128, fp16_no_flatten_grads=False, fp16_scale_tolerance=0.0, fp16_scale_window=None, fp32_reduce_scatter=False, gen_subset='test', gpt2_encoder_json='https://dl.fbaipublicfiles.com/fairseq/gpt2_bpe/encoder.json', gpt2_vocab_bpe='https://dl.fbaipublicfiles.com/fairseq/gpt2_bpe/vocab.bpe', heartbeat_timeout=-1, input_size=None, keep_best_checkpoints=-1, keep_interval_updates=-1, keep_interval_updates_pattern=-1, keep_last_epochs=-1, layernorm_embedding=False, load_checkpoint_on_all_dp_ranks=False, localsgd_frequency=3, log_file=None, log_format='tqdm', log_interval=10, lr=[5e-05], lr_scheduler='inverse_sqrt', max_epoch=10, max_target_positions=1024, max_tgt_len=64, max_tokens=None, max_tokens_valid=None, max_update=0, max_valid_steps=None, maximize_best_checkpoint_metric=False, memory_efficient_bf16=False, memory_efficient_fp16=False, min_loss_scale=0.0001, min_params_to_wrap=100000000, model_parallel_size=1, no_cross_attention=False, no_epoch_checkpoints=False, no_last_checkpoints=False, no_progress_bar=False, no_reshard_after_forward=False, no_save=False, no_save_optimizer_state=False, no_scale_embedding=False, no_seed_provided=False, no_token_positional_embeddings=False, nprocs_per_node=8, num_shards=1, num_workers=10, offload_activations=False, optimizer='adam', optimizer_overrides='{}', pad=1, patience=-1, pipeline_balance=None, pipeline_checkpoint='never', pipeline_chunks=0, pipeline_decoder_balance=None, pipeline_decoder_devices=None, pipeline_devices=None, pipeline_encoder_balance=None, pipeline_encoder_devices=None, pipeline_model_parallel=False, plasma_path='/tmp/plasma', preprocess='DA2', profile=False, quant_noise_pq=0, quant_noise_pq_block_size=8, quant_noise_scalar=0, quantization_config_path=None, recount=1, remode='pixel', repeated_aug=True, reprob=0.25, required_batch_size_multiple=8, required_seq_len_multiple=1, reset_dataloader=False, reset_logging=False, reset_lr_scheduler=False, reset_meters=False, reset_optimizer=False, resplit=False, restore_file='checkpoint_last.pt', save_dir='/mnt/minghaoli/model/DeiTTR/2MCDIP_BSZ16_LR5E_5_UP4_ITP_BEiT_LargeR_DA2', save_interval=1, save_interval_updates=5000, scoring='bleu', seed=1111, sentence_avg=False, shard_id=0, share_all_embeddings=False, share_decoder_input_output_embed=False, skip_invalid_size_inputs_valid_test=False, slowmo_algorithm='LocalSGD', slowmo_momentum=None, smoothing=0.1, stop_min_lr=-1.0, stop_time_hours=0, suppress_crashes=False, task='text_recognition', tensorboard_logdir='/home/t-minghl/tensorboard/6c2625382c6ef931a888b88f8ab0ca6c/logs/2MCDIP_BSZ16_LR5E_5_UP4_ITP_BEiT_LargeR_DA2', text_recog_gen=False, threshold_loss_scale=None, tie_adaptive_weights=False, tokenizer=None, tpu=False, train_interpolation='bicubic', train_subset='train', unk=3, update_freq=[4], use_bmuf=False, use_old_adam=False, use_plasma_view=False, user_dir='./ViT-TR', valid_subset='valid', validate_after_updates=0, validate_interval=1, validate_interval_updates=5000, wandb_project=None, warmup_init_lr=1e-08, warmup_updates=800, weight_decay=0.0001, write_checkpoints_asynchronously=False, zero_sharding='none'). Available models: dict_keys(['wav2vec', 'wav2vec2', 'wav2vec_ctc', 'wav2vec_seq2seq', 'transformer_lm']) Requested model type: DeiT_TR_larger
```

**To Reproduce**
1. Download [trocr-base-stage1.pt](https://layoutlm.blob.core.windows.net/trocr/model_zoo/fairseq/trocr-base-stage1.pt)
2. Try to run `pic_inference.py` on an image of a textline

**Expected behavior**
Model file should have a name that matches the registered DeiT models so it can be loaded successfully. Alternatively `deit_models.py` should register the name the base model was given.

- Platform: Ubuntu 20.04
- Python version: 3.7
- PyTorch version (GPU?): 1.7.1 (RTX 3090)

**Comment by Dod-o** [comment]
@Lauler  fixed, thanks~
