### ISSUE TITLE
[LayoutReader] RuntimeError: "pow" not implemented for 'Half'

### ISSUE THREAD

**Issue by WhoAteDaCake** [microsoft/unilm#489]
**Describe the bug**
Model I am using **LayoutReader**

The problem arises when using:
* [x] the official example scripts: (give details below)
* [ ] my own modified scripts: (give details below)

**To Reproduce**
1. Download test dataset
2. Run the step **4 Decoding**
3. Error is thrown 

```
Traceback (most recent call last):
  File "decode_seq2seq.py", line 344, in <module>
    main()
  File "decode_seq2seq.py", line 277, in main
    traces = model(input_ids, token_type_ids,
  File "/home/augustinas/.pyenv/versions/generic/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/augustinas/open-source/unilm/layoutreader/s2s_ft/modeling_decoding.py", line 1221, in forward
    self.bert(x_input_ids, curr_token_type_ids, curr_position_ids, curr_attention_mask,
  File "/home/augustinas/.pyenv/versions/generic/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/augustinas/open-source/unilm/layoutreader/s2s_ft/modeling_decoding.py", line 1113, in forward
    embedding_output = self.embeddings(
  File "/home/augustinas/.pyenv/versions/generic/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/augustinas/open-source/unilm/layoutreader/s2s_ft/modeling_decoding.py", line 399, in forward
    embeddings = self.LayerNorm(embeddings)
  File "/home/augustinas/.pyenv/versions/generic/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/augustinas/open-source/unilm/layoutreader/s2s_ft/modeling_decoding.py", line 228, in forward
    s = (x - u).pow(2).mean(-1, keepdim=True)
RuntimeError: "pow" not implemented for 'Half'

```

**Expected behavior**

- Platform: Ubuntu 20.04
- Python version: Python 3.8.9
- PyTorch version (GPU?): torch-1.7.1 (CPU)

**Comment by HYPJUDY** [comment]
We suggest you to run the code with GPUs, since the code was only tested with GPUs and some unexpected errors may occur with CPUs.

**Comment by hoangson13** [comment]
removing arg --fp16 you can run on cpu
