### ISSUE TITLE
HTTPError(req.full_url, code, msg, hdrs, fp) urllib.error.HTTPError: HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by acer22969** [microsoft/unilm#514]
**Describe the bug**
Model I am using (trocr-base-handwritten.pt):

**To Reproduce**
1. install success
2. run : python pic_inference.py

**Expected behavior**
Traceback (most recent call last):
  File "pic_inference.py", line 70, in <module>
    model, cfg, task, generator, bpe, img_transform, device = init(model_path, beam)
  File "pic_inference.py", line 15, in init
    arg_overrides={"beam": beam, "task": "text_recognition", "data": "", "fp16": False})
  File "/home/jimmy/anaconda3/envs/trocr/lib/python3.7/site-packages/fairseq/checkpoint_utils.py", line 387, in load_model_ensemble_and_task
    model = task.build_model(cfg.model)
  File "/home/jimmy/anaconda3/envs/trocr/lib/python3.7/site-packages/fairseq/tasks/fairseq_task.py", line 633, in build_model
    model = models.build_model(args, self)
  File "/home/jimmy/anaconda3/envs/trocr/lib/python3.7/site-packages/fairseq/models/__init__.py", line 96, in build_model
    return model.build_model(cfg, task)
  File "/home/jimmy/Desktop/trocr/unilm/trocr/deit_models.py", line 427, in build_model
    roberta = torch.hub.load('pytorch/fairseq', 'roberta.large')
  File "/home/jimmy/anaconda3/envs/trocr/lib/python3.7/site-packages/torch/hub.py", line 368, in load
    repo_or_dir = _get_cache_or_reload(repo_or_dir, force_reload, verbose)
  File "/home/jimmy/anaconda3/envs/trocr/lib/python3.7/site-packages/torch/hub.py", line 141, in _get_cache_or_reload
    download_url_to_file(url, cached_file, progress=False)
  File "/home/jimmy/anaconda3/envs/trocr/lib/python3.7/site-packages/torch/hub.py", line 425, in download_url_to_file
    u = urlopen(req)
  File "/home/jimmy/anaconda3/envs/trocr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/jimmy/anaconda3/envs/trocr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/jimmy/anaconda3/envs/trocr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/jimmy/anaconda3/envs/trocr/lib/python3.7/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/home/jimmy/anaconda3/envs/trocr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/home/jimmy/anaconda3/envs/trocr/lib/python3.7/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/home/jimmy/anaconda3/envs/trocr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/jimmy/anaconda3/envs/trocr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/jimmy/anaconda3/envs/trocr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/home/jimmy/anaconda3/envs/trocr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/home/jimmy/anaconda3/envs/trocr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

And I fixed by change deit_models.py line 418~429
```  
if specified:
      pretrained_model = pretrained_model.replace('-', '.')
      logger.info('Load pre-trained decoder parameters from {}'.format(pretrained_model))
      roberta = torch.hub.load('pytorch/fairseq', pretrained_model)
  elif args.decoder_layers == 6:
      logger.info('Load pre-trained decoder parameters from roberta.base')
      roberta = torch.hub.load('pytorch/fairseq', 'roberta.base')
  elif args.decoder_layers == 12:
      logger.info('Load pre-trained decoder parameters from roberta.large')
      roberta = torch.hub.load('pytorch/fairseq', 'roberta.large')
  else:
      raise AttributeError('Cannot determind the pre-trained model')
```
to 
```  
if specified:
      pretrained_model = pretrained_model.replace('-', '.')
      logger.info('Load pre-trained decoder parameters from {}'.format(pretrained_model))
      roberta = torch.hub.load('pytorch/fairseq:main', pretrained_model)
  elif args.decoder_layers == 6:
      logger.info('Load pre-trained decoder parameters from roberta.base')
      roberta = torch.hub.load('pytorch/fairseq:main', 'roberta.base')
  elif args.decoder_layers == 12:
      logger.info('Load pre-trained decoder parameters from roberta.large')
      roberta = torch.hub.load('pytorch/fairseq:main', 'roberta.large')
  else:
      raise AttributeError('Cannot determind the pre-trained model')
```
- Platform: ubuntu 14.04
- Python version: 3.7
- PyTorch version (GPU?): 3.7.11 (GPU:TAITAN)

**Comment by zeekling** [comment]
its redis problem.

**Comment by yngalxx** [comment]
I think that lines 502-513 should also be changed in exactly the same way as 418-429.

**Comment by acer22969** [comment]
Thanks for @yngalxx  fixed

**Comment by KHOI769** [comment]
Hello, I'm looking for a problem related to installing PyAudio plugin for Python, this is why I need to:
 error: subprocess-exited-with-error
  × Running setup.py install for PyAudio did not run successfully.
  exit code: 1
  > [11 lines of output]
Can you help me please.
