### ISSUE TITLE
I can't run run_xfun_er.py, as XFUND dataset is not downloadable through the code

### ISSUE THREAD

**Issue by yuhao1982** [microsoft/unilm#517]
I run run_fun_er.py in layoutlmv2 code, but actually the XFUN dataset is not downloadable, as the following errors show:

Traceback (most recent call last):

  File "run_xfun_re.py", line 253, in <module>

    main()

  File "run_xfun_re.py", line 98, in main

    datasets = load_dataset('xfun', 'xfun.zh')

  File "/home/yuhao/.local/lib/python3.7/site-packages/datasets/load.py", line 751, in load_dataset

    use_auth_token=use_auth_token,

  File "/home/yuhao/.local/lib/python3.7/site-packages/datasets/builder.py", line 575, in download_and_prepare

    dl_manager=dl_manager, verify_infos=verify_infos, **download_and_prepare_kwargs

  File "/home/yuhao/.local/lib/python3.7/site-packages/datasets/builder.py", line 652, in _download_and_prepare

    self._prepare_split(split_generator, **prepare_split_kwargs)

  File "/home/yuhao/.local/lib/python3.7/site-packages/datasets/builder.py", line 980, in _prepare_split

    generator, unit=" examples", total=split_info.num_examples, leave=False, disable=not_verbose

  File "/home/yuhao/.local/lib/python3.7/site-packages/tqdm/std.py", line 1133, in __iter__

    for obj in iterable:

  File "/home/yuhao/.cache/huggingface/modules/datasets_modules/datasets/xfun/417563ea53b3d4eb66554cefe9d10246e8c7346176cc9e671986c571d0eb2712/xfun.py", line 110, in _generate_examples

    data = json.load(f)

  File "/usr/local/lib/python3.7/json/__init__.py", line 296, in load

    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)

  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads

    return _default_decoder.decode(s)

  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode

    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode

    raise JSONDecodeError("Expecting value", s, err.value) from None

json.decoder.JSONDecodeError: Expecting value: line 7 column 1 (char 6)

The original link _URL = "https://github.com/doc-analysis/XFUN/releases/download/v1.0/" is actually not working (it is outdated), but if we simply use code: datasets.load_dataset('xfun', 'xfun.zh') or change the link to _URL = "https://github.com/doc-analysis/XFUND/releases/tag/v1.0" which is in the XFUN GitHub: https://github.com/doc-analysis/XFUND, the errors of above show up !

Does anyone have the same issue or how to resolve this problem ?

**Comment by vincezengqiang** [comment]
hi,  have you ever tried downloading the XFUND dataset by yourself and load it from local?

**Comment by yuhao1982** [comment]
yes. it is ok now.



发自 网易邮箱大师




---- 回复的原邮件 ----
| 发件人 | vince ***@***.***> |
| 日期 | 2021年11月24日 09:40 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [microsoft/unilm] Serious problem in LayoutLMv2: I can't run run_xfun_er.py, as XFUND dataset is not downloadable through the code (Issue #517) |

hi, have you ever tried downloading the XFUND dataset by yourself and load it from local?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by vincezengqiang** [comment]
`def load_from_disk(dataset_path: str, fs=None, keep_in_memory: Optional[bool] = None) -> Union[Dataset, DatasetDict]`

through this interface?

**Comment by yuhao1982** [comment]
load_dataset(path+"layoutlmft/data/datasets/xfun.py"，localdata_dir)

you're supposed to change xfun.py  accordingly



发自 网易邮箱大师




---- 回复的原邮件 ----
| 发件人 | vince ***@***.***> |
| 日期 | 2021年11月24日 09:48 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [microsoft/unilm] Serious problem in LayoutLMv2: I can't run run_xfun_er.py, as XFUND dataset is not downloadable through the code (Issue #517) |

def load_from_disk(dataset_path: str, fs=None, keep_in_memory: Optional[bool] = None) -> Union[Dataset, DatasetDict]

through this interface?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by vincezengqiang** [comment]
thx a lot, I change the code, it work now!

**Comment by ZeningLin** [comment]
change the variable _URL in huggingface/modules/datasets_modules/datasets/xfun/xxxxxxxxxx/xfun.py to "https://github.com/doc-analysis/XFUND/releases/download/v1.0/"
