### ISSUE TITLE
Error in inferencing using dit object detection models

### ISSUE THREAD

**Issue by Atul997** [microsoft/unilm#746]
I have finetune icdar19 model checkpoint  on 2 custom classes. While inferencing I am getting following error- 

    Traceback (most recent call last):
    "inference.py", line 79, in <module>
     main()
     File "inference.py", line 46, in main
    cfg.merge_from_file(args.config_file)
    File "/usr/local/lib/python3.7/dist-packages/detectron2/config/config.py", line 69, in merge_from_file
    self.merge_from_other_cfg(loaded_cfg)
    File "/usr/local/lib/python3.7/dist-packages/fvcore/common/config.py", line 132, in merge_from_other_cfg
    return super().merge_from_other_cfg(cfg_other)
    File "/usr/local/lib/python3.7/dist-packages/yacs/config.py", line 217, in merge_from_other_cfg
    _merge_a_into_b(cfg_other, self, self, [])
    File "/usr/local/lib/python3.7/dist-packages/yacs/config.py", line 478, in _merge_a_into_b
    _merge_a_into_b(v, b[k], root, key_list + [k])
    File "/usr/local/lib/python3.7/dist-packages/yacs/config.py", line 478, in _merge_a_into_b
    _merge_a_into_b(v, b[k], root, key_list + [k])
    File "/usr/local/lib/python3.7/dist-packages/yacs/config.py", line 474, in _merge_a_into_b
    v = _check_and_coerce_cfg_value_type(v, b[k], k, full_key)
    File "/usr/local/lib/python3.7/dist-packages/yacs/config.py", line 537, in _check_and_coerce_cfg_value_type
    original_type, replacement_type, original, replacement, full_key
    ValueError: Type mismatch (<class 'str'> vs. <class 'dict'>) with values ({} vs. {}) for config key: MODEL.VIT.MODEL_KWARGS

`python inference.py --image_path /path/to/image --output_file_name  result.jpg --config-file /path/to/config.yaml`

I used config file generated during model training.

**Comment by Dod-o** [comment]
Hi @Atul997, I want to make sure that inference on our released model is OK, but inference on the model which you fine-tuned would occur this error?

**Comment by Atul997** [comment]
Yes the inference on released model is OK. I changed the config file and it worked. 
@Dod-o  Thanks for the reply.

**Comment by fidhaph** [comment]
@Atul997 how did you modify config file?

**Comment by lyj3534** [comment]
Hi @fidhaph,
I don't know if this will help, but I solved it like this.
I just deleted "MODEL_KWARGS: '{}'" from the config file.
