### ISSUE TITLE
ERROR in TROCR installation

### ISSUE THREAD

**Issue by shenw000** [microsoft/unilm#779]
To install trocr on Ubuntu 20.04, I followed the trocr installation steps on https://github.com/microsoft/unilm/tree/master/trocr

conda create -n trocr python=3.7
conda activate trocr
git clone https://github.com/microsoft/unilm.git
cd unilm
cd trocr
pip install pybind11
pip install -r requirements.txt
pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" 'git+https://github.com/NVIDIA/apex.git'

Every goes well until I ran the installation script of trocr, pip install -r requirements.txt
I encountered the following error

========================================================================
INFO: pip is looking at multiple versions of fastwer to determine which version is compatible with other requirements. This could take a while.
Collecting fastwer
  Using cached fastwer-0.1.tar.gz (3.6 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-p201j4px/fastwer_063feafc5a6f4f29a4b5e94054f4c21a/setup.py", line 93, in <module>
          with open('LICENSE') as f:
      FileNotFoundError: [Errno 2] No such file or directory: 'LICENSE'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

========================================================================

I searched the Internet for possible solutions, but didn't see any.
I did upgraded the pip to version 22.1.2

**Comment by dka-lmis** [comment]
As a temporary hotfix you can 
- install a newer version of fastwer (I had no issues with 0.1.3) 
- change commit from the latest version of Fairseq to a version from when the current TrOCR version was released 
 (18. March) 
git+https://github.com/pytorch/fairseq.git@b554f5ec9067c2f88bf17a736ddb57ea1cab14cc
- remove the specific version from pytorch, torchvision and timm in the requirements.txt

I was able to at least pull and set up the environment 

(if anyone wants to use it under windows: Open the PowerShell as root)

**Comment by bit-scientist** [comment]
Hi, @dka-lmis, I know it's been over a year. I hope it's still relevant to you 😃 
I did as you suggested, but still the same error occured. Could you please share your `requirements.txt` file for reference?

Right now, I am trying to install the dependencies one by one, so it would also be great to know what versions of dependencies you got over there. Thank you!

**Comment by haojianqi1** [comment]
https://wiki.python.org/moin/WindowsCompilers
watch this and download 
then solved
