### ISSUE TITLE
LayoutLMv3: IndexError: index out of range in self on some inputs

### ISSUE THREAD

**Issue by HonzaCech** [microsoft/unilm#821]
**Describe the bug**
Model I am using (UniLM, MiniLM, LayoutLM ...): 
LayoutLMv3

The problem arises when using:
*  my own modified scripts: (give details below)

I'm using LayoutLMv3 from huggingface transformers - https://huggingface.co/docs/transformers/model_doc/layoutlmv3#transformers.LayoutLMv3Model - and I am getting an "IndexError: index out of range in self" on some inputs. It works fine for some inputs, but fails for others. I found a similar issue here -https://github.com/microsoft/unilm/issues/771 - but there, the problem was with bboxes. However, I am using the full processor with OCR that creates the bounding boxes for me, so my only actual input are PIL images.
I initialize the processor with 
`processor = AutoProcessor.from_pretrained("microsoft/layoutlmv3-base", apply_ocr=True)`
and the call it with
`processor(img1, return_tensors="np", padding='max_length')` (img1 is PIL image)
The full stack trace is
```
Traceback (most recent call last):
  File "/home/h/projects/layoutLM/main_layoutLM.py", line 58, in <module>
    main()
  File "/home/h/projects/layoutLM/main_layoutLM.py", line 37, in main
    output1, output2 = net(img0, img1)
  File "/home/h/projects/layoutLM/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/h/projects/layoutLM/layoutlm_classifier_contrastive.py", line 36, in forward
    output1 = self.forward_once(input1)
  File "/home/h/projects/layoutLM/layoutlm_classifier_contrastive.py", line 29, in forward_once
    output = self.layout_LM(**x)
  File "/home/h/projects/layoutLM/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/h/projects/layoutLM/venv/lib/python3.9/site-packages/transformers/models/layoutlmv3/modeling_layoutlmv3.py", line 833, in forward
    embedding_output = self.embeddings(
  File "/home/h/projects/layoutLM/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/h/projects/layoutLM/venv/lib/python3.9/site-packages/transformers/models/layoutlmv3/modeling_layoutlmv3.py", line 261, in forward
    position_embeddings = self.position_embeddings(position_ids)
  File "/home/h/projects/layoutLM/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/h/projects/layoutLM/venv/lib/python3.9/site-packages/torch/nn/modules/sparse.py", line 158, in forward
    return F.embedding(
  File "/home/h/projects/layoutLM/venv/lib/python3.9/site-packages/torch/nn/functional.py", line 2199, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
IndexError: index out of range in self

Process finished with exit code 1

```
where `output = self.layout_LM(**x)` is the actual calling of LayoutLM, which is created by
`self.layout_LM = AutoModel.from_pretrained("microsoft/layoutlmv3-base")`
I have no idea what could be wrong, as I said, it works fine for some inputs and I don't see anything special about cases where it fails 

- Platform: Ubuntu 20.04
- Python version: 3.9
- PyTorch version (GPU?): 1.12.0+cpu

**Comment by HYPJUDY** [comment]
This problem seems to be caused by some position_ids being larger than the embedding size. I suggest you find the exact sample causing this problem and analyze its minimum and maximum indices. You can also check some related answers [here](https://discuss.pytorch.org/t/embeddings-index-out-of-range-error/12582) and [here](https://discuss.pytorch.org/t/embedding-error-index-out-of-range-in-self/81550/16).

**Comment by HYPJUDY** [comment]
I am closing this issue for now, since it is inactive.
