### ISSUE TITLE
BEiT v2 Semantic Segmentation  `BEiT: __init__() got an unexpected keyword argument 'rel_pos_bias_interpolation_type'`

### ISSUE THREAD

**Issue by XHMY** [microsoft/unilm#864]
**Describe the bug**
Model I am using (UniLM, MiniLM, LayoutLM ...): beit2

The problem arises when using:
the official example scripts: (give details below)
```shell
./tools/dist_train.sh \
configs/beit/upernet/upernet_beit_base_12_512_slide_160k_21ktoade20k.py 4 \
--work-dir outputs --seed 123 \
--options model.pretrained=https://conversationhub.blob.core.windows.net/beit-share-public/beitv2/beitv2_base_patch16_224_pt1k_ft21k.pth
```

When I run the training script, it show:

```shell
Traceback (most recent call last):
  File "./tools/train.py", line 167, in <module>
    main()
  File "./tools/train.py", line 134, in main
    model = build_segmentor(
  File "/root/opt/miniconda3/envs/torch_lts_1.8.2/lib/python3.8/site-packages/mmseg/models/builder.py", line 66, in build_segmentor
    return build(cfg, SEGMENTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/root/opt/miniconda3/envs/torch_lts_1.8.2/lib/python3.8/site-packages/mmseg/models/builder.py", line 33, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/root/opt/miniconda3/envs/torch_lts_1.8.2/lib/python3.8/site-packages/mmcv/utils/registry.py", line 182, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: EncoderDecoder: BEiT: __init__() got an unexpected keyword argument 'rel_pos_bias_interpolation_type'
Traceback (most recent call last):
  File "/root/opt/miniconda3/envs/torch_lts_1.8.2/lib/python3.8/site-packages/mmcv/utils/registry.py", line 179, in build_from_cfg
    return obj_cls(**args)
TypeError: __init__() got an unexpected keyword argument 'rel_pos_bias_interpolation_type'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/opt/miniconda3/envs/torch_lts_1.8.2/lib/python3.8/site-packages/mmcv/utils/registry.py", line 179, in build_from_cfg
    return obj_cls(**args)
  File "/root/opt/miniconda3/envs/torch_lts_1.8.2/lib/python3.8/site-packages/mmseg/models/segmentors/encoder_decoder.py", line 30, in __init__
    self.backbone = builder.build_backbone(backbone)
  File "/root/opt/miniconda3/envs/torch_lts_1.8.2/lib/python3.8/site-packages/mmseg/models/builder.py", line 38, in build_backbone
    return build(cfg, BACKBONES)
  File "/root/opt/miniconda3/envs/torch_lts_1.8.2/lib/python3.8/site-packages/mmseg/models/builder.py", line 33, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/root/opt/miniconda3/envs/torch_lts_1.8.2/lib/python3.8/site-packages/mmcv/utils/registry.py", line 182, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: BEiT: __init__() got an unexpected keyword argument 'rel_pos_bias_interpolation_type'
```

**To Reproduce**
1. Run the above script

**Expected behavior**
The training starts

- Platform: Ubuntu 16.04.7 LTS
- Python version: 3.8.13
- PyTorch version (GPU?): 1.8.2  cuda 10.2
- mmcv-full 1.3.0
- mmsegmentation 1.11.0
- apex 0.1

**Comment by pengzhiliang** [comment]
Thank for your attention~

You could remove `rel_pos_bias_interpolation_type=0` in the config file `configs/beit/upernet/upernet_beit_base_12_512_slide_160k_21ktoade20k.py`.

**Comment by XHMY** [comment]
> Thank for your attention~
> 
> You could remove `rel_pos_bias_interpolation_type=0` in the config file `configs/beit/upernet/upernet_beit_base_12_512_slide_160k_21ktoade20k.py`.

Thank for your relpy~

I removed that and started training. But I still have some trouble to reproduce the results on ADE20k.

The result I got was:

```
+--------+------+-------+-------+
| Scope  | mIoU | mAcc  | aAcc  |
+--------+------+-------+-------+
| global | 52.7 | 63.97 | 84.39 |
+--------+------+-------+-------+
```

The `mIoU` is `4.84` lower than your results (`57.54`). I only change two settings:

- Set the `samples_per_gpu` to 4 to ensure same efficient batch size on 4 GPU.
- Remove `--seed 0  --deterministic` for fast traning.

[20220913_141418.log](https://github.com/microsoft/unilm/files/9590869/20220913_141418.log)
[20220913_141418.log.json.txt](https://github.com/microsoft/unilm/files/9590870/20220913_141418.log.json.txt)

**Comment by pengzhiliang** [comment]
Hello,

We report 57.54\% mIoU by using the larger size, so you can check it again. I will check the hyper-parameters I used. And I will release the training log after I prepare.

Thanks~

**Comment by XHMY** [comment]
I trained it with 8 V100 and `--seed 0 --deterministic`, but could not reproduce your results either.
[20220921_202702.log](https://github.com/microsoft/unilm/files/9624364/20220921_202702.log)


<img width="927" alt="image" src="https://user-images.githubusercontent.com/28671304/191710893-08191be2-8675-40eb-ae33-df2b0925fbf0.png">

**Comment by XHMY** [comment]
I used to train with BEiTv2-base, thereby the `57.54` mIoU can not be reproduced. I train with BEiTv2-large now and get `Iter(val) [144000]	mIoU: 0.5761, mAcc: 0.6929, aAcc: 0.8608`.

Thanks for your reply~
