### ISSUE TITLE
change bbox shape in layoutlmv3, but raise errors

### ISSUE THREAD

**Issue by jack-gits** [microsoft/unilm#869]
whether I can use the 4 points for the box? like [2031, 426, 2129, 432, 2128, 454, 2029, 449].

when I change to above shape of box, I found padding still padding 4 digits [0,0,0,0], so that it raise an error as following.

Traceback (most recent call last):
  File "run_train.py", line 89, in <module>
    example = train_dataset[0]
  File "/home/ubuntu/anaconda3/envs/layoutlmv3/lib/python3.7/site-packages/datasets/arrow_dataset.py", line 2125, in __getitem__
    key,
  File "/home/ubuntu/anaconda3/envs/layoutlmv3/lib/python3.7/site-packages/datasets/arrow_dataset.py", line 2110, in _getitem
    pa_subtable, key, formatter=formatter, format_columns=format_columns, output_all_columns=output_all_columns
  File "/home/ubuntu/anaconda3/envs/layoutlmv3/lib/python3.7/site-packages/datasets/formatting/formatting.py", line 532, in format_table
    return formatter(pa_table, query_type=query_type)
  File "/home/ubuntu/anaconda3/envs/layoutlmv3/lib/python3.7/site-packages/datasets/formatting/formatting.py", line 281, in __call__
    return self.format_row(pa_table)
  File "/home/ubuntu/anaconda3/envs/layoutlmv3/lib/python3.7/site-packages/datasets/formatting/formatting.py", line 310, in format_row
    row = self.python_arrow_extractor().extract_row(pa_table)
  File "/home/ubuntu/anaconda3/envs/layoutlmv3/lib/python3.7/site-packages/datasets/formatting/formatting.py", line 140, in extract_row
    return _unnest(pa_table.to_pydict())
  File "pyarrow/table.pxi", line 3945, in pyarrow.lib.Table.to_pydict
  File "pyarrow/table.pxi", line 1258, in pyarrow.lib.ChunkedArray.to_pylist
  File "/home/ubuntu/anaconda3/envs/layoutlmv3/lib/python3.7/site-packages/datasets/features/features.py", line 645, in to_pylist
    return self.to_numpy(zero_copy_only=zero_copy_only).tolist()
  File "/home/ubuntu/anaconda3/envs/layoutlmv3/lib/python3.7/site-packages/datasets/features/features.py", line 607, in to_numpy
    numpy_arr = numpy_arr.reshape(len(self) - len(null_indices), *self.type.shape)
ValueError: cannot reshape array of size 4088 into shape (1,512,8)

**Comment by HYPJUDY** [comment]
The bounding box representation of LayoutLMv3 is based on two points. If you have four points, please use two of them. Otherwise, you need to modify the [code](https://github.com/microsoft/unilm/blob/74ae0ed7287d0eabb11c32922e8b88aef0f8c839/layoutlmv3/layoutlmft/models/layoutlmv3/modeling_layoutlmv3.py#L105-L130) and re-train the model.
