### ISSUE TITLE
Ask for the environment when running beit/semantic_segmentation

### ISSUE THREAD

**Issue by JiahangXu** [microsoft/unilm#912]
**Describe**
Model I am using (UniLM, MiniLM, LayoutLM ...):BEiT

Sorry to disturb. I'm going to reproduce the semantic segmentation task in [unilm](https://github.com/microsoft/unilm)/[beit](https://github.com/microsoft/unilm/tree/master/beit)/semantic_segmentation/ . However, I haven't found the correct env versions to make no bug for `mmseg`/`mmcv`/`apex`/`torch` packages and python version. Could you please share all your package version in your experiment with me?
I'm trying these configs combination:
```text
pytorch==1.9.1
mmsegmentation==0.11.1
mmcv-full==1.3.0
apex=20.44-dev
```

and my bug now is:
```text
Traceback (most recent call last):
  File "/home/jiahangxu/miniconda3/envs/py37/lib/python3.7/site-packages/mmcv/utils/registry.py", line 179, in build_from_cfg
    return obj_cls(**args)
  File "/home/jiahangxu/miniconda3/envs/py37/lib/python3.7/site-packages/mmseg/models/decode_heads/uper_head.py", line 34, in __init__
    align_corners=self.align_corners)
  File "/home/jiahangxu/miniconda3/envs/py37/lib/python3.7/site-packages/mmseg/models/decode_heads/psp_head.py", line 44, in __init__
    act_cfg=self.act_cfg)))
  File "/home/jiahangxu/miniconda3/envs/py37/lib/python3.7/site-packages/mmcv/cnn/bricks/conv_module.py", line 147, in __init__
    self.norm_name, norm = build_norm_layer(norm_cfg, norm_channels)
  File "/home/jiahangxu/miniconda3/envs/py37/lib/python3.7/site-packages/mmcv/cnn/bricks/norm.py", line 110, in build_norm_layer
    layer._specify_ddp_gpu_num(1)
  File "/home/jiahangxu/miniconda3/envs/py37/lib/python3.7/site-packages/mmcv/utils/parrots_wrapper.py", line 87, in _specify_ddp_gpu_num
    super()._specify_ddp_gpu_num(gpu_size)
AttributeError: 'super' object has no attribute '_specify_ddp_gpu_num'
```

Just FYI, I'm using python==3.7.0 now, and I tried 3.8.0 & 3.9.0 there are bugs when running ``from mmseg.apis import set_random_seed``.

Thanks a lot and looking forward to your reply!

**Comment by JiahangXu** [comment]
@donglixp Sorry to disturb the author and wish you all well!

**Comment by addf400** [comment]
Hi @JiahangXu ,
Thanks for your kind words, I found a similar [issue](https://github.com/open-mmlab/mmocr/issues/325) that may help you to fix this.

Solution 1: downgrading the version of pytorch
Solution 2: from this [comment](https://github.com/open-mmlab/mmocr/issues/325#issuecomment-867719744)
```
had the same issue!
resolved after changing type to 'BN' in norm_cfg=dict(type='SyncBN', requires_grad=True),
```
