### ISSUE TITLE
Error while fine tunning with s2s-ft

### ISSUE THREAD

**Issue by deepaknlp** [microsoft/unilm#99]
Hi @donglixp
I wanted to fine-tune the [minilm model](https://1drv.ms/u/s!AjHn0yEmKG8qixAYyu2Fvq5ulnU7?e=DFApTA) using `run_seq2seq.py`. However, I am getting the following error:
```
Traceback (most recent call last):
  File "run_seq2seq.py", line 420, in <module>
    main()
  File "run_seq2seq.py", line 403, in main
    model, tokenizer = get_model_and_tokenizer(args)
  File "run_seq2seq.py", line 390, in get_model_and_tokenizer
    cache_dir=args.cache_dir if args.cache_dir else None)
  File "/home1/deepak/Documents/MQG/unilm/s2s-ft/s2s_ft/modeling.py", line 90, in from_pretrained
    if kwargs["state_dict"] is None:
KeyError: 'state_dict'
```
It seems the pre-trained minilm model missing the `state_dict` which is required while using `s2s-ft` package.

Please suggest me the solution.

**Comment by addf400** [comment]
@deepaknlp Can you provide your running command and your running log (std output)?

**Comment by deepaknlp** [comment]
Hi @addf400 ,
Thank you for the prompt response.
The running command is:
```
TRAIN_FILE=train.json
# folder used to save fine-tuned checkpoints
OUTPUT_DIR=save_checkpoints
# folder used to cache package dependencies
CACHE_DIR=transformer_package_cache

export CUDA_VISIBLE_DEVICES=5
python -m torch.distributed.launch --nproc_per_node=1 run_seq2seq.py \
  --train_file ${TRAIN_FILE} --output_dir ${OUTPUT_DIR} \
  --model_type minilm --model_name_or_path MiniLM-L12-H384-uncased \
  --do_lower_case --fp16 --fp16_opt_level O2 --max_source_seq_length 464 --max_target_seq_length 48 \
  --per_gpu_train_batch_size 16 --gradient_accumulation_steps 1 \
  --learning_rate 7e-5 --num_warmup_steps 1 --num_training_steps 30 --cache_dir ${CACHE_DIR}
```

and the running log is:

```
04/01/2020 22:22:28 - WARNING - __main__ -   Process rank: 0, device: cuda:0, n_gpu: 1, distributed training: True, 16-bits training: True
04/01/2020 22:22:28 - INFO - __main__ -   Training/evaluation parameters Namespace(adam_epsilon=1e-08, cache_dir='transformer_package_cache', cached_train_features_file=None, config_name=None, device=device(type='cuda', index=0), do_lower_case=True, fp16=True, fp16_opt_level='O2', gradient_accumulation_steps=1, keep_prob=0.1, label_smoothing=0.1, learning_rate=7e-05, local_rank=0, log_dir=None, logging_steps=500, max_grad_norm=1.0, max_source_seq_length=464, max_target_seq_length=48, model_name_or_path='MiniLM-L12-H384-uncased', model_type='unilm', n_gpu=1, no_cuda=False, num_training_epochs=10, num_training_steps=30, num_warmup_steps=1, output_dir='save_checkpoints', per_gpu_train_batch_size=16, random_prob=0.1, save_steps=1500, seed=42, server_ip='', server_port='', tokenizer_name=None, train_file='train.json', weight_decay=0.01)
04/01/2020 22:22:28 - INFO - transformers.configuration_utils -   loading configuration file MiniLM-L12-H384-uncased/config.json
04/01/2020 22:22:28 - INFO - transformers.configuration_utils -   Model config UnilmConfig {
  "_num_labels": 2,
  "architectures": null,
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": null,
  "decoder_start_token_id": null,
  "do_sample": false,
  "early_stopping": false,
  "eos_token_id": null,
  "finetuning_task": null,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 384,
  "id2label": {
    "0": "LABEL_0",
    "1": "LABEL_1"
  },
  "initializer_range": 0.02,
  "intermediate_size": 1536,
  "is_decoder": false,
  "is_encoder_decoder": false,
  "label2id": {
    "LABEL_0": 0,
    "LABEL_1": 1
  },
  "layer_norm_eps": 1e-12,
  "length_penalty": 1.0,
  "max_length": 20,
  "max_position_embeddings": 512,
  "min_length": 0,
  "model_type": "",
  "no_repeat_ngram_size": 0,
  "num_attention_heads": 12,
  "num_beams": 1,
  "num_hidden_layers": 12,
  "num_return_sequences": 1,
  "output_attentions": false,
  "output_hidden_states": false,
  "output_past": true,
  "pad_token_id": null,
  "prefix": null,
  "pruned_heads": {},
  "repetition_penalty": 1.0,
  "source_type_id": 0,
  "target_type_id": 1,
  "task_specific_params": null,
  "temperature": 1.0,
  "top_k": 50,
  "top_p": 1.0,
  "torchscript": false,
  "type_vocab_size": 2,
  "use_bfloat16": false,
  "vocab_size": 30522
}

04/01/2020 22:22:28 - INFO - __main__ -   Model config for seq2seq: BertForSeq2SeqConfig {
  "_num_labels": 2,
  "architectures": null,
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": null,
  "decoder_start_token_id": null,
  "do_sample": false,
  "early_stopping": false,
  "eos_token_id": null,
  "finetuning_task": null,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 384,
  "id2label": {
    "0": "LABEL_0",
    "1": "LABEL_1"
  },
  "initializer_range": 0.02,
  "intermediate_size": 1536,
  "is_decoder": false,
  "is_encoder_decoder": false,
  "label2id": {
    "LABEL_0": 0,
    "LABEL_1": 1
  },
  "label_smoothing": 0.1,
  "layer_norm_eps": 1e-12,
  "length_penalty": 1.0,
  "max_length": 20,
  "max_position_embeddings": 512,
  "min_length": 0,
  "model_type": "bert",
  "no_repeat_ngram_size": 0,
  "num_attention_heads": 12,
  "num_beams": 1,
  "num_hidden_layers": 12,
  "num_return_sequences": 1,
  "output_attentions": false,
  "output_hidden_states": false,
  "output_past": true,
  "pad_token_id": 0,
  "prefix": null,
  "pruned_heads": {},
  "repetition_penalty": 1.0,
  "source_type_id": 0,
  "target_type_id": 1,
  "task_specific_params": null,
  "temperature": 1.0,
  "top_k": 50,
  "top_p": 1.0,
  "torchscript": false,
  "type_vocab_size": 2,
  "use_bfloat16": false,
  "vocab_size": 30522,
  "vocab_size_or_config_json_file": 30522
}

04/01/2020 22:22:28 - INFO - transformers.tokenization_utils -   Model name 'MiniLM-L12-H384-uncased' not found in model shortcut name list (unilm-large-cased, unilm-base-cased, unilm1-large-cased, unilm1-base-cased, unilm1.2-base-uncased). Assuming 'MiniLM-L12-H384-uncased' is a path, a model identifier, or url to a directory containing tokenizer files.
04/01/2020 22:22:28 - INFO - transformers.tokenization_utils -   Didn't find file MiniLM-L12-H384-uncased/added_tokens.json. We won't load it.
04/01/2020 22:22:28 - INFO - transformers.tokenization_utils -   Didn't find file MiniLM-L12-H384-uncased/special_tokens_map.json. We won't load it.
04/01/2020 22:22:28 - INFO - transformers.tokenization_utils -   Didn't find file MiniLM-L12-H384-uncased/tokenizer_config.json. We won't load it.
04/01/2020 22:22:28 - INFO - transformers.tokenization_utils -   loading file MiniLM-L12-H384-uncased/vocab.txt
04/01/2020 22:22:28 - INFO - transformers.tokenization_utils -   loading file None
04/01/2020 22:22:28 - INFO - transformers.tokenization_utils -   loading file None
04/01/2020 22:22:28 - INFO - transformers.tokenization_utils -   loading file None
Traceback (most recent call last):
  File "run_seq2seq.py", line 420, in <module>
    main()
  File "run_seq2seq.py", line 403, in main
    model, tokenizer = get_model_and_tokenizer(args)
  File "run_seq2seq.py", line 390, in get_model_and_tokenizer
    cache_dir=args.cache_dir if args.cache_dir else None)
  File "/home1/deepak/Documents/MQG/unilm/s2s-ft/s2s_ft/modeling.py", line 90, in from_pretrained
    if kwargs["state_dict"] is None:
KeyError: 'state_dict'
```

**Comment by addf400** [comment]
> MiniLM-L12-H384-uncased

Hi @deepaknlp ,
You can change '--model_name_or_path MiniLM-L12-H384-uncased' into ''--model_name_or_path minilm-l12-h384-uncased' (lower case), should be work.

**Comment by deepaknlp** [comment]
Thank you, @addf400.
It worked.
